{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libBaseUtils",
    "version": "2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "androidx.documentfile",
          "module": "documentfile",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.google.android.things",
          "module": "androidthings",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.0.0-alpha.14"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.0.0-alpha.14"
          }
        }
      ],
      "files": [
        {
          "name": "libBaseUtils-2.2.aar",
          "url": "libBaseUtils-2.2.aar",
          "size": 121843,
          "sha512": "9f3a30de5fefb6a8f5ef0362cfa724b03b19b766fd2d1ef6c910f1e00244dcbcdf5826d563f407be8a7823efc79f0d24b5847f34baa76b35f54a990896305a7c",
          "sha256": "a568eea4f7d4520ab83295c5bd9d50a272a42c7d44290bb3d0f097a675dcc5d7",
          "sha1": "df0ade03bde5aa76b8931888f6700fffbbff9169",
          "md5": "07528b56835ecb25dcf0996d0d01d69c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "2.0.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "androidx.documentfile",
          "module": "documentfile",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.google.android.things",
          "module": "androidthings",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.0.0-alpha.14"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.0.0-alpha.14"
          }
        }
      ],
      "files": [
        {
          "name": "libBaseUtils-2.2.aar",
          "url": "libBaseUtils-2.2.aar",
          "size": 121843,
          "sha512": "9f3a30de5fefb6a8f5ef0362cfa724b03b19b766fd2d1ef6c910f1e00244dcbcdf5826d563f407be8a7823efc79f0d24b5847f34baa76b35f54a990896305a7c",
          "sha256": "a568eea4f7d4520ab83295c5bd9d50a272a42c7d44290bb3d0f097a675dcc5d7",
          "sha1": "df0ade03bde5aa76b8931888f6700fffbbff9169",
          "md5": "07528b56835ecb25dcf0996d0d01d69c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "libBaseUtils-2.2-sources.jar",
          "url": "libBaseUtils-2.2-sources.jar",
          "size": 68544,
          "sha512": "4ba4b72e696c438320daf6e6d36469efba10912912b8cd6c5f90fdf64c3f9ccee0395932c6689fc49532def91d0cd1e442ff7271539b9688fe9b2e479f99a722",
          "sha256": "5cbc55d91ce89f7318f1642ad16045bb1148ea56d49275d730c5c445ab9f6302",
          "sha1": "8e00711b17eb32187ed41996183198b83368208b",
          "md5": "afc5271d3d6994fe94363bfd69555611"
        }
      ]
    }
  ]
}
