{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libBaseUtils",
    "version": "2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "androidx.documentfile",
          "module": "documentfile",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.google.android.things",
          "module": "androidthings",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.0.0-alpha.14"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.0.0-alpha.14"
          }
        }
      ],
      "files": [
        {
          "name": "libBaseUtils-2.2.aar",
          "url": "libBaseUtils-2.2.aar",
          "size": 117404,
          "sha512": "63addafae3924eaaae683b0c2c5beb7ddcf681d2ec47afeb3d04d52dd8013f6bff6ed14b057eb5620eee0c8a240977d8a42f2eb2c794b08627b4689e595c4b2d",
          "sha256": "fd55ad38c024c07b9c0877a009dfc2f4c348169b56e4b248ed80247ef7020fa1",
          "sha1": "83ede1a79c103d5b31682339c558e4d6459d6c38",
          "md5": "2e4788d7a1c9e729a61181e0fb6e44cf"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "2.0.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "androidx.documentfile",
          "module": "documentfile",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.google.android.things",
          "module": "androidthings",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.0.0-alpha.14"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.0.0-alpha.14"
          }
        }
      ],
      "files": [
        {
          "name": "libBaseUtils-2.2.aar",
          "url": "libBaseUtils-2.2.aar",
          "size": 117404,
          "sha512": "63addafae3924eaaae683b0c2c5beb7ddcf681d2ec47afeb3d04d52dd8013f6bff6ed14b057eb5620eee0c8a240977d8a42f2eb2c794b08627b4689e595c4b2d",
          "sha256": "fd55ad38c024c07b9c0877a009dfc2f4c348169b56e4b248ed80247ef7020fa1",
          "sha1": "83ede1a79c103d5b31682339c558e4d6459d6c38",
          "md5": "2e4788d7a1c9e729a61181e0fb6e44cf"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "libBaseUtils-2.2-sources.jar",
          "url": "libBaseUtils-2.2-sources.jar",
          "size": 66127,
          "sha512": "84564966383d39c71e585dc085e1b5d0deae6e03a31d5f33a1a5b9c772f0d039d81255df9f08c1309ff9df72c5f6c09a1f21b4de8efa2db744c44518d8ea8fbd",
          "sha256": "1a9bc9e9dbf449846a06c574eb5cf7d01a578b4cffd59cd9dfa802a6ed110580",
          "sha1": "c004da1252f1d38df0443892f08d512582e3f8d2",
          "md5": "c8c535ce04df27a41bb0187c902a14f8"
        }
      ]
    }
  ]
}
