{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libSessionUtils",
    "version": "2.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libSessionUtils-2.7.aar",
          "url": "libSessionUtils-2.7.aar",
          "size": 109560,
          "sha512": "3740eb2f012e33d90e707123ade35a7d1bfd4c70d26e8c3dc5e942beacdd2b2d2c800bdb9ea64e5a0a67ddac4c7392d54239fce3ed326226c09acac9925fdf6f",
          "sha256": "365446baacb9a63925248e6ea46e3b1adfb4138796854fa535a1a748adcca977",
          "sha1": "5ce23b920b30e31c75d02968ad7a2d1fc56ea111",
          "md5": "0b6374b512b012e2fe7c15627cbf3e24"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.zhuchao.android",
          "module": "libEventInterface",
          "version": {
            "requires": "1.6"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libFBaseUitls",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libJOSUtils",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libINetUtils",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libMediaUtils",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libPlayerUtils",
          "version": {
            "requires": "2.6"
          }
        }
      ],
      "files": [
        {
          "name": "libSessionUtils-2.7.aar",
          "url": "libSessionUtils-2.7.aar",
          "size": 109560,
          "sha512": "3740eb2f012e33d90e707123ade35a7d1bfd4c70d26e8c3dc5e942beacdd2b2d2c800bdb9ea64e5a0a67ddac4c7392d54239fce3ed326226c09acac9925fdf6f",
          "sha256": "365446baacb9a63925248e6ea46e3b1adfb4138796854fa535a1a748adcca977",
          "sha1": "5ce23b920b30e31c75d02968ad7a2d1fc56ea111",
          "md5": "0b6374b512b012e2fe7c15627cbf3e24"
        }
      ]
    }
  ]
}
