{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libSessionUtils",
    "version": "2.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libSessionUtils-2.7.aar",
          "url": "libSessionUtils-2.7.aar",
          "size": 85656,
          "sha512": "7ba9749089546e7437d276de5510b817b87e23d80ff787ccb990d5594e571e2228b44797d7ac146e539f95d9e5a43a4a8b2a5b18e577ca0c2878fee5dcaf23d0",
          "sha256": "f9f74c434193a32f0acb93615840bf143631f2dcb208117da6aa3d0f556ea61b",
          "sha1": "2391e5e88b6ad5d63c4a72beafb176af549594c5",
          "md5": "12f1e7c1e4e7f2bbc783b09c80f88ac0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.zhuchao.android",
          "module": "libCallbackEvent",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libFileUtils",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libJOSUtils",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libINetUtils",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libMediaUtils",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libPlayerUtils",
          "version": {
            "requires": "2.6"
          }
        }
      ],
      "files": [
        {
          "name": "libSessionUtils-2.7.aar",
          "url": "libSessionUtils-2.7.aar",
          "size": 85656,
          "sha512": "7ba9749089546e7437d276de5510b817b87e23d80ff787ccb990d5594e571e2228b44797d7ac146e539f95d9e5a43a4a8b2a5b18e577ca0c2878fee5dcaf23d0",
          "sha256": "f9f74c434193a32f0acb93615840bf143631f2dcb208117da6aa3d0f556ea61b",
          "sha1": "2391e5e88b6ad5d63c4a72beafb176af549594c5",
          "md5": "12f1e7c1e4e7f2bbc783b09c80f88ac0"
        }
      ]
    }
  ]
}
