{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libSessionUtils",
    "version": "2.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libSessionUtils-2.7.aar",
          "url": "libSessionUtils-2.7.aar",
          "size": 105351,
          "sha512": "c31d217bffb59296f65f56433fa8326ea9f51f55d892c3fb8aaa826630f69436be615384efb8be479b95336b5eea5d7473d8a0f4dcc458f67aa9da45f5d5ed2c",
          "sha256": "0aea96557ed28e4147a4ec8991ad61fefb081c322beb6772a1fb158ef33dd876",
          "sha1": "50c405fd875830fdedae8347a75a6245878fee81",
          "md5": "1f76b9d37171ac6852ca852d9e5fd71e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.zhuchao.android",
          "module": "libFBaseUtils",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libJOSUtils",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libINetUtils",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libMediaUtils",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libPlayerUtils",
          "version": {
            "requires": "2.8"
          }
        }
      ],
      "files": [
        {
          "name": "libSessionUtils-2.7.aar",
          "url": "libSessionUtils-2.7.aar",
          "size": 105351,
          "sha512": "c31d217bffb59296f65f56433fa8326ea9f51f55d892c3fb8aaa826630f69436be615384efb8be479b95336b5eea5d7473d8a0f4dcc458f67aa9da45f5d5ed2c",
          "sha256": "0aea96557ed28e4147a4ec8991ad61fefb081c322beb6772a1fb158ef33dd876",
          "sha1": "50c405fd875830fdedae8347a75a6245878fee81",
          "md5": "1f76b9d37171ac6852ca852d9e5fd71e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "libSessionUtils-2.7-sources.jar",
          "url": "libSessionUtils-2.7-sources.jar",
          "size": 39980,
          "sha512": "aaef11fa4f92a232577c22aefc65289baa69c947f33a96d00dcdc9bc89525be29c2bd3d3fe5ecf34accb6c90f40e2a4f428b173778e5499e7bdc64b402a866cc",
          "sha256": "752eb6d4d042e058c82629584e78f27d20581ca354c8e91e90c594e905012794",
          "sha1": "775b2e057d2cc5abeedf1c28c7fb94ab5de7742c",
          "md5": "f8d5557b4bbedf8b018f27c3eac188af"
        }
      ]
    }
  ]
}
