{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libPlayerUtils",
    "version": "2.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.zhuchao.android",
          "module": "libDecodeCore",
          "version": {
            "requires": "2.1"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libCallbackEvent",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libFileUtils",
          "version": {
            "requires": "1.6"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libJosUtils",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "libPlayerUtils-2.4.aar",
          "url": "libPlayerUtils-2.4.aar",
          "size": 31959,
          "sha512": "466518e6531a64af66366ded4f4976cb71b3f781c24a40f82550fce148be634f9167dd65f6faf9d406335b44e8e2ecfb4ec6f6ac27cedcc914bc17f3b7e24443",
          "sha256": "ad03ef4670492be6b04c0a8fe82c81e5764c41a9bb377b3534e85e9fa58ceffa",
          "sha1": "6b106aff2804b457819b1a4168e5d0b0e84486b1",
          "md5": "4b6731a0b0ae0434a0a79f51b8602943"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.zhuchao.android",
          "module": "libDecodeCore",
          "version": {
            "requires": "2.1"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libCallbackEvent",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libFileUtils",
          "version": {
            "requires": "1.6"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libJosUtils",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "libPlayerUtils-2.4.aar",
          "url": "libPlayerUtils-2.4.aar",
          "size": 31959,
          "sha512": "466518e6531a64af66366ded4f4976cb71b3f781c24a40f82550fce148be634f9167dd65f6faf9d406335b44e8e2ecfb4ec6f6ac27cedcc914bc17f3b7e24443",
          "sha256": "ad03ef4670492be6b04c0a8fe82c81e5764c41a9bb377b3534e85e9fa58ceffa",
          "sha1": "6b106aff2804b457819b1a4168e5d0b0e84486b1",
          "md5": "4b6731a0b0ae0434a0a79f51b8602943"
        }
      ]
    }
  ]
}
