{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libNetUtil",
    "version": "2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libNetUtil-2.0.aar",
          "url": "libNetUtil-2.0.aar",
          "size": 49770,
          "sha512": "e467eb30104d8d8a4f2bc0fda596d258b1ed1e69588e9f6cffbf027dcd8eb27a09d7b89bcf8f1e3237119434083a10b593b341bcc0fb83544e74e8484709c929",
          "sha256": "c04c87026fd03d6164921f25c0a1ba4bc99cad542d99272604c7095df1cb4338",
          "sha1": "f67b1790799e46e15225f6fd18435a2e47727a3f",
          "md5": "71460c2529a959121e79cde40da71c29"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.zhuchao.android",
          "module": "libFileUtils",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libCallbackEvent",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "me.jessyan",
          "module": "progressmanager",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.8"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "org.conscrypt",
          "module": "conscrypt-openjdk-uber",
          "version": {
            "requires": "1.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "libNetUtil-2.0.aar",
          "url": "libNetUtil-2.0.aar",
          "size": 49770,
          "sha512": "e467eb30104d8d8a4f2bc0fda596d258b1ed1e69588e9f6cffbf027dcd8eb27a09d7b89bcf8f1e3237119434083a10b593b341bcc0fb83544e74e8484709c929",
          "sha256": "c04c87026fd03d6164921f25c0a1ba4bc99cad542d99272604c7095df1cb4338",
          "sha1": "f67b1790799e46e15225f6fd18435a2e47727a3f",
          "md5": "71460c2529a959121e79cde40da71c29"
        }
      ]
    }
  ]
}
