{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libNetUtil",
    "version": "2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libNetUtil-2.0.aar",
          "url": "libNetUtil-2.0.aar",
          "size": 47544,
          "sha512": "ce92030f238972e3593f8878735d695309567e931333bc54e89d1ec322cbe126ec1861d0f499309804934f6e2dc93f4dd6f7274fb3625cfef27df86f97c4d71f",
          "sha256": "9e11148f03361a16c589d0e4b734387677ce95562da08cfe9e2f46347889e444",
          "sha1": "a914739794f544868fbee6fde987318638d2ab63",
          "md5": "c22a9af230350e984397384c3ffc3461"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.zhuchao.android",
          "module": "libFileUtils",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libCallbackEvent",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.8"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "libNetUtil-2.0.aar",
          "url": "libNetUtil-2.0.aar",
          "size": 47544,
          "sha512": "ce92030f238972e3593f8878735d695309567e931333bc54e89d1ec322cbe126ec1861d0f499309804934f6e2dc93f4dd6f7274fb3625cfef27df86f97c4d71f",
          "sha256": "9e11148f03361a16c589d0e4b734387677ce95562da08cfe9e2f46347889e444",
          "sha1": "a914739794f544868fbee6fde987318638d2ab63",
          "md5": "c22a9af230350e984397384c3ffc3461"
        }
      ]
    }
  ]
}
