{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libFBaseUtils",
    "version": "2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.0-alpha01"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0-alpha02"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.google.android.things",
          "module": "androidthings",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.0.0-alpha.11"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.0.0-alpha.11"
          }
        }
      ],
      "files": [
        {
          "name": "libFBaseUtils-2.0.aar",
          "url": "libFBaseUtils-2.0.aar",
          "size": 101074,
          "sha512": "ed325c8a690f22e7c3216bb4781aaee7187259d5e60802f0c3a4ac6b3f7251c9aba1549fd33835fabe62492e0a65df247a07846e7f9ff8c32e320470a5d62ed1",
          "sha256": "a11f87f6de850cd84656a415aa7679ad7a03abf74c8a1352b5433a73125224c2",
          "sha1": "7dbf7ad7127581b32370a5d0e0ee41c5c87394d1",
          "md5": "0cf77eb4414c9bf8fcc8145be483b118"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.0-alpha01"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0-alpha02"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.google.android.things",
          "module": "androidthings",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.0.0-alpha.11"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.0.0-alpha.11"
          }
        }
      ],
      "files": [
        {
          "name": "libFBaseUtils-2.0.aar",
          "url": "libFBaseUtils-2.0.aar",
          "size": 101074,
          "sha512": "ed325c8a690f22e7c3216bb4781aaee7187259d5e60802f0c3a4ac6b3f7251c9aba1549fd33835fabe62492e0a65df247a07846e7f9ff8c32e320470a5d62ed1",
          "sha256": "a11f87f6de850cd84656a415aa7679ad7a03abf74c8a1352b5433a73125224c2",
          "sha1": "7dbf7ad7127581b32370a5d0e0ee41c5c87394d1",
          "md5": "0cf77eb4414c9bf8fcc8145be483b118"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "libFBaseUtils-2.0-sources.jar",
          "url": "libFBaseUtils-2.0-sources.jar",
          "size": 54532,
          "sha512": "7fdf83cb8e166a6ed5050619da8ba4f17cbc63c976bcbf37cd92c67cf0c240f66d7489884095957712f576250ad2f2c6a5e01898b80aefd28e27fbcde73aac11",
          "sha256": "148d9834fbfac89010d848285c2313a5ae06739a1cb6b57f4f24812768742115",
          "sha1": "02487e605dc0830f68d9f71d95662043a4c50e66",
          "md5": "22203065e7e785292c3d35df2a682159"
        }
      ]
    }
  ]
}
