{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libFBaseUtils",
    "version": "2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0-alpha02"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.google.android.things",
          "module": "androidthings",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.0.0-alpha.11"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.0.0-alpha.11"
          }
        }
      ],
      "files": [
        {
          "name": "libFBaseUtils-2.0.aar",
          "url": "libFBaseUtils-2.0.aar",
          "size": 101310,
          "sha512": "92dde77837c84b57a379655d291aaddbafada1287b66ae949a0c46944583c1bbbaf4bca938a2db411be0d0de05c7ff1846aeb9387ac289a68f3e9d5692c98f33",
          "sha256": "821a68b0c83e071e25d7c569bcd47a094a2bc1b253cc1daa1e3a85985eb7f041",
          "sha1": "941a8a2e55903827af713e130c48293f80a94417",
          "md5": "17a9b60d09c6dd1c3942e2a8a997a9a4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0-alpha02"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.google.android.things",
          "module": "androidthings",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.0.0-alpha.11"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.0.0-alpha.11"
          }
        }
      ],
      "files": [
        {
          "name": "libFBaseUtils-2.0.aar",
          "url": "libFBaseUtils-2.0.aar",
          "size": 101310,
          "sha512": "92dde77837c84b57a379655d291aaddbafada1287b66ae949a0c46944583c1bbbaf4bca938a2db411be0d0de05c7ff1846aeb9387ac289a68f3e9d5692c98f33",
          "sha256": "821a68b0c83e071e25d7c569bcd47a094a2bc1b253cc1daa1e3a85985eb7f041",
          "sha1": "941a8a2e55903827af713e130c48293f80a94417",
          "md5": "17a9b60d09c6dd1c3942e2a8a997a9a4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "libFBaseUtils-2.0-sources.jar",
          "url": "libFBaseUtils-2.0-sources.jar",
          "size": 54711,
          "sha512": "b56b6d43ad88b1f4ec36c9304e588d705cc187343f003a56ba46d572f8638194092d90921125086d6acd7d30094407216580533123f290d0bace8a3573f26554",
          "sha256": "a7607ae58e10d05dbf86fce4e20969cca43b7df8bfbab871f978cf78693646d3",
          "sha1": "d59154e8a49733051f434c37d069f19494fc091f",
          "md5": "070beb7d51db52e5e352a1f222aa67bc"
        }
      ]
    }
  ]
}
