{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libFBaseUtils",
    "version": "2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.0-alpha01"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0-alpha02"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.google.android.things",
          "module": "androidthings",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.0.0-alpha.11"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.0.0-alpha.11"
          }
        }
      ],
      "files": [
        {
          "name": "libFBaseUtils-2.0.aar",
          "url": "libFBaseUtils-2.0.aar",
          "size": 99756,
          "sha512": "708b54d15062eb82735f390200d11f96d298ef16b3a1b043f327447dca356506005aabccceaf71dfc2c350547553e5da98c42fa3cabfe5c72634c2a6407e0586",
          "sha256": "dbc2fb9d3bd2c723c8fc104bfb896c5b1da62a0be68e8f7e3307953df058fb7e",
          "sha1": "e4418d0ac0b371459408efa8d4fde9ba734243d2",
          "md5": "32a189b8987fe2e6318d49050d5f4fa1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.0-alpha01"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0-alpha02"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.google.android.things",
          "module": "androidthings",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.0.0-alpha.11"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.0.0-alpha.11"
          }
        }
      ],
      "files": [
        {
          "name": "libFBaseUtils-2.0.aar",
          "url": "libFBaseUtils-2.0.aar",
          "size": 99756,
          "sha512": "708b54d15062eb82735f390200d11f96d298ef16b3a1b043f327447dca356506005aabccceaf71dfc2c350547553e5da98c42fa3cabfe5c72634c2a6407e0586",
          "sha256": "dbc2fb9d3bd2c723c8fc104bfb896c5b1da62a0be68e8f7e3307953df058fb7e",
          "sha1": "e4418d0ac0b371459408efa8d4fde9ba734243d2",
          "md5": "32a189b8987fe2e6318d49050d5f4fa1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "libFBaseUtils-2.0-sources.jar",
          "url": "libFBaseUtils-2.0-sources.jar",
          "size": 54343,
          "sha512": "3b78320aa150d68e2b101b9adca173f5407410bee3a22419bc945cd9341513211a20a7812933bc7ac07ebf899811939aaf48cb128b416026f0ab910c97eef294",
          "sha256": "9a5156eeea9819e3e7c3ed0b0acc87573ccc8c818052f529d528895340ca52c5",
          "sha1": "02f55cdafa168827fef407ca3b68c816a37dd4f8",
          "md5": "706d8115db4d434e817bfe80513f1d5c"
        }
      ]
    }
  ]
}
