{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libOpenComputerVision",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "libOpenComputerVision-1.0.aar",
          "url": "libOpenComputerVision-1.0.aar",
          "size": 45701403,
          "sha512": "7f468a774b7e6bc30461997bcec844edf200578ec7088a2eda4cecea6d16851f7cdc541ec4d532b084a6c612050868966346e59793e570e128670c2cb923cfd0",
          "sha256": "d36f21432104b19215b0737b7df91ac00cf59109e4fe78d806a6db156f0229b1",
          "sha1": "58281dce58ecb75cc1000e76c32dc30d4dcd8086",
          "md5": "52c6c388cc8b151f70a214495adc2b34"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "libOpenComputerVision-1.0.aar",
          "url": "libOpenComputerVision-1.0.aar",
          "size": 45701403,
          "sha512": "7f468a774b7e6bc30461997bcec844edf200578ec7088a2eda4cecea6d16851f7cdc541ec4d532b084a6c612050868966346e59793e570e128670c2cb923cfd0",
          "sha256": "d36f21432104b19215b0737b7df91ac00cf59109e4fe78d806a6db156f0229b1",
          "sha1": "58281dce58ecb75cc1000e76c32dc30d4dcd8086",
          "md5": "52c6c388cc8b151f70a214495adc2b34"
        }
      ]
    }
  ]
}
