{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libOpenComputerVision",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "libOpenComputerVision-1.0.aar",
          "url": "libOpenComputerVision-1.0.aar",
          "size": 42432326,
          "sha512": "c46928bdb7eb9c32235fe7f32278cbff38e793ebf652260662fb1e04294517ffb94befaf272873c8e442b7e3110634789ee8d9760a85f9987a380e65c9e8bd51",
          "sha256": "eeae2a014816bc5082800be2d000bdc15b46f596f837e45b9451fb61c1e007c1",
          "sha1": "c08cc12f15449b5f7bf019dd14f727174d9b0d32",
          "md5": "442fcfecd4099e673d12fa3c2574b1ec"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "libOpenComputerVision-1.0.aar",
          "url": "libOpenComputerVision-1.0.aar",
          "size": 42432326,
          "sha512": "c46928bdb7eb9c32235fe7f32278cbff38e793ebf652260662fb1e04294517ffb94befaf272873c8e442b7e3110634789ee8d9760a85f9987a380e65c9e8bd51",
          "sha256": "eeae2a014816bc5082800be2d000bdc15b46f596f837e45b9451fb61c1e007c1",
          "sha1": "c08cc12f15449b5f7bf019dd14f727174d9b0d32",
          "md5": "442fcfecd4099e673d12fa3c2574b1ec"
        }
      ]
    }
  ]
}
