{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libOpenComputerVision",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "libOpenComputerVision-1.0.aar",
          "url": "libOpenComputerVision-1.0.aar",
          "size": 55821739,
          "sha512": "c507c6fed47b7815dc2c69dff29b037362502035a1ebd7e24053527137408bfa887b67498ba81f77c81c800b858110a94784acfd799176ed1412a605ecf75f91",
          "sha256": "aa434a9bddade8c87451d5124814d63361fe90b94195d76cb70fb0ad8c56c0d5",
          "sha1": "efe51bdb480888c7f4d52a54e87d563534c0b242",
          "md5": "05959c6c6d7a68eb7bfbac153f4932c1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "libOpenComputerVision-1.0.aar",
          "url": "libOpenComputerVision-1.0.aar",
          "size": 55821739,
          "sha512": "c507c6fed47b7815dc2c69dff29b037362502035a1ebd7e24053527137408bfa887b67498ba81f77c81c800b858110a94784acfd799176ed1412a605ecf75f91",
          "sha256": "aa434a9bddade8c87451d5124814d63361fe90b94195d76cb70fb0ad8c56c0d5",
          "sha1": "efe51bdb480888c7f4d52a54e87d563534c0b242",
          "md5": "05959c6c6d7a68eb7bfbac153f4932c1"
        }
      ]
    }
  ]
}
