{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libPlayerUtils",
    "version": "2.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libPlayerUtils-2.8.aar",
          "url": "libPlayerUtils-2.8.aar",
          "size": 202682,
          "sha512": "324cc4052e55187a208056adeedf77fa477143e253e76bcfa043407c7e07bb33c97e8cac814c1d2c0e1795b09c7be332654a710f95d08fdfe33a4357e1e36994",
          "sha256": "e19961668a5ab62122854697c65478f5f8507995890fd11b66765c9f0d3be59c",
          "sha1": "42e64c415e287eb944a69ed117cb8dc5fbd2afa1",
          "md5": "e39a99b4016efef1bb181db7bc8344d6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.zhuchao.android",
          "module": "libFBaseUtils",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libINetUtils",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libJOSUtils",
          "version": {
            "requires": "1.3"
          }
        }
      ],
      "files": [
        {
          "name": "libPlayerUtils-2.8.aar",
          "url": "libPlayerUtils-2.8.aar",
          "size": 202682,
          "sha512": "324cc4052e55187a208056adeedf77fa477143e253e76bcfa043407c7e07bb33c97e8cac814c1d2c0e1795b09c7be332654a710f95d08fdfe33a4357e1e36994",
          "sha256": "e19961668a5ab62122854697c65478f5f8507995890fd11b66765c9f0d3be59c",
          "sha1": "42e64c415e287eb944a69ed117cb8dc5fbd2afa1",
          "md5": "e39a99b4016efef1bb181db7bc8344d6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "libPlayerUtils-2.8-sources.jar",
          "url": "libPlayerUtils-2.8-sources.jar",
          "size": 18164,
          "sha512": "2bcd08fe3b3e58f967a67fc6c22517e5fca17f6347cc5feb3b77117df91fa99f889cf9090fadff60ef2e8e972ff921628c977d2cc3b5a1efbda1535887446f71",
          "sha256": "85c00c363d349b6fb97504e6c1b12f9981c0943d6f083403437a1382db13e79c",
          "sha1": "edc947320ba625bd79f3605796d0704401fc2cd3",
          "md5": "2bc2cf25903585239a6eaeb037e787b6"
        }
      ]
    }
  ]
}
