{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libPlayerUtils",
    "version": "2.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libPlayerUtils-2.8.aar",
          "url": "libPlayerUtils-2.8.aar",
          "size": 202350,
          "sha512": "a8d521e183843ddcc407a3c5ae144d2d6ed9591a1762189633dc39fb916b6991b516057fb19427ff027da8e77c894c71f544db592c3acfa6803de4a809bb61a0",
          "sha256": "ba6517f69a2704ad8b650a63df6a8f20f2dabd45ebf238177bfd1e56186a19f8",
          "sha1": "a6ba24fdb301370c600c2852b3004caa2fbb96a7",
          "md5": "38bc8b09423f843dde03b2d437e07ff4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.zhuchao.android",
          "module": "libFBaseUtils",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libINetUtils",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libJOSUtils",
          "version": {
            "requires": "1.3"
          }
        }
      ],
      "files": [
        {
          "name": "libPlayerUtils-2.8.aar",
          "url": "libPlayerUtils-2.8.aar",
          "size": 202350,
          "sha512": "a8d521e183843ddcc407a3c5ae144d2d6ed9591a1762189633dc39fb916b6991b516057fb19427ff027da8e77c894c71f544db592c3acfa6803de4a809bb61a0",
          "sha256": "ba6517f69a2704ad8b650a63df6a8f20f2dabd45ebf238177bfd1e56186a19f8",
          "sha1": "a6ba24fdb301370c600c2852b3004caa2fbb96a7",
          "md5": "38bc8b09423f843dde03b2d437e07ff4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "libPlayerUtils-2.8-sources.jar",
          "url": "libPlayerUtils-2.8-sources.jar",
          "size": 18014,
          "sha512": "4832ba5dce91d0e0019ecd7cda31cb982067a9b2a75375b94bfd49f5d9efa799eac23efe76ecef6c1699c0b53e8af97d789fdfc1c0465469f8ac68bd7c8fc07f",
          "sha256": "d8b6c3107184b5b9fe24a2f3fc52539870534893f85d2cf1361061e5107acb4b",
          "sha1": "11393fde9b88a53970bcf9e6b418adca4307b888",
          "md5": "8d0ad42b30ff1248b23a99a6e60c041c"
        }
      ]
    }
  ]
}
