{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libPlayerUtils",
    "version": "2.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libPlayerUtils-2.8.aar",
          "url": "libPlayerUtils-2.8.aar",
          "size": 202389,
          "sha512": "ec93c2c5dd2188c690f424bbdea9c1981e2907a362001a0b9c39a5de976b886bcd48a669fe0dfb4451b6cdda762fdf396256903a96acacc27887760fc5b7b25e",
          "sha256": "ab5837b3ec51a8ed31391da8ae08a82e5580841804d46e49b1bcaaca05925487",
          "sha1": "b8ca9e741414cd22c8be9a2519d7638b12265328",
          "md5": "6702b8a08b696e5c9b9aea52b21ca43d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.zhuchao.android",
          "module": "libFBaseUtils",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libINetUtils",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libJOSUtils",
          "version": {
            "requires": "1.3"
          }
        }
      ],
      "files": [
        {
          "name": "libPlayerUtils-2.8.aar",
          "url": "libPlayerUtils-2.8.aar",
          "size": 202389,
          "sha512": "ec93c2c5dd2188c690f424bbdea9c1981e2907a362001a0b9c39a5de976b886bcd48a669fe0dfb4451b6cdda762fdf396256903a96acacc27887760fc5b7b25e",
          "sha256": "ab5837b3ec51a8ed31391da8ae08a82e5580841804d46e49b1bcaaca05925487",
          "sha1": "b8ca9e741414cd22c8be9a2519d7638b12265328",
          "md5": "6702b8a08b696e5c9b9aea52b21ca43d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "libPlayerUtils-2.8-sources.jar",
          "url": "libPlayerUtils-2.8-sources.jar",
          "size": 18024,
          "sha512": "6ba64290ebe43da4b9a1d8a2d4b92c6401eb57f43054fd33aada30e1f11bf7dabb56f457d95be708ac10fb36ecfb2d9f664fd11a9fd9bc80cf25b7947cb86c75",
          "sha256": "d0a90c42e0786820683116b337ed817e7f4ab2fd1b612e84e9eaf2e2af2e45e0",
          "sha1": "bc882b6e4b6d716faaf0de9916fea3c68f1df7e6",
          "md5": "7e5310bad524469b4cb916af02460f4f"
        }
      ]
    }
  ]
}
