{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libPlayerUtils",
    "version": "2.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libPlayerUtils-2.6.aar",
          "url": "libPlayerUtils-2.6.aar",
          "size": 212746,
          "sha512": "f3126a6b6576ee4490fc3dafefc28cca982845e854a202935139f849fb9e54409db6d0d9d13bd546761f592c83db25ec2932621b383ed085eb911f280bbe7016",
          "sha256": "1024fdd107c5dc06cfd732bb3c4e127e6f59106edd108cf0a508802a3bb47cb4",
          "sha1": "449e5997b081eab363d086d018007bc163ff3537",
          "md5": "120b34992edf7882c53271887b1b339a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.zhuchao.android",
          "module": "libDecodeCore",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libEventInterface",
          "version": {
            "requires": "1.6"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libFBaseUitls",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libINetUtils",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libJOSUtils",
          "version": {
            "requires": "1.2"
          }
        }
      ],
      "files": [
        {
          "name": "libPlayerUtils-2.6.aar",
          "url": "libPlayerUtils-2.6.aar",
          "size": 212746,
          "sha512": "f3126a6b6576ee4490fc3dafefc28cca982845e854a202935139f849fb9e54409db6d0d9d13bd546761f592c83db25ec2932621b383ed085eb911f280bbe7016",
          "sha256": "1024fdd107c5dc06cfd732bb3c4e127e6f59106edd108cf0a508802a3bb47cb4",
          "sha1": "449e5997b081eab363d086d018007bc163ff3537",
          "md5": "120b34992edf7882c53271887b1b339a"
        }
      ]
    }
  ]
}
