{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libPlayerUtils",
    "version": "2.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libPlayerUtils-2.6.aar",
          "url": "libPlayerUtils-2.6.aar",
          "size": 212676,
          "sha512": "3cd96d2e27525805af221f8b959ccd283cde127d1225fceea2b57d02e223581d252d254d51e883a70ae951601fbddea397b009876504e8b6f6154b7f7ea7f00b",
          "sha256": "c55b509e73478e31b6d099fcb2612bf7fbb47a33ca508a49a6d66609832d9b36",
          "sha1": "b4505e8bb94cb9cc534d37cae214b2ffdfb13a17",
          "md5": "aa2a3d26a1c95b4ac1e656ee10d32939"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.videolan.android",
          "module": "libvlc-all",
          "version": {
            "requires": "3.5.0-eap8"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libINetUtils",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libCallbackEvent",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libFileUtils",
          "version": {
            "requires": "1.6"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libJOSUtils",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "libPlayerUtils-2.6.aar",
          "url": "libPlayerUtils-2.6.aar",
          "size": 212676,
          "sha512": "3cd96d2e27525805af221f8b959ccd283cde127d1225fceea2b57d02e223581d252d254d51e883a70ae951601fbddea397b009876504e8b6f6154b7f7ea7f00b",
          "sha256": "c55b509e73478e31b6d099fcb2612bf7fbb47a33ca508a49a6d66609832d9b36",
          "sha1": "b4505e8bb94cb9cc534d37cae214b2ffdfb13a17",
          "md5": "aa2a3d26a1c95b4ac1e656ee10d32939"
        }
      ]
    }
  ]
}
