{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libPlayerUtils",
    "version": "2.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libPlayerUtils-2.6.aar",
          "url": "libPlayerUtils-2.6.aar",
          "size": 212814,
          "sha512": "66d9f743117ea67460cf234d683369bc4f500d0f03bafd616b30aa1c6344779d3919b928b6ff05b1be2570d4d537d8959b6f1694e342f5bc76ae19e7d454d9cc",
          "sha256": "9b39b26f4b2eb0eea1cc8e80d9cd2cd8b84ed6f3faf74dc04ba221a5f3330882",
          "sha1": "ec387220287bcba0d005cc8a9d341db3924ed8bd",
          "md5": "c9b0c06827ccc7aaa5202633770cceb7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.zhuchao.android",
          "module": "libDecodeCore",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libINetUtils",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libCallbackEvent",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libFileUtils",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libJOSUtils",
          "version": {
            "requires": "1.2"
          }
        }
      ],
      "files": [
        {
          "name": "libPlayerUtils-2.6.aar",
          "url": "libPlayerUtils-2.6.aar",
          "size": 212814,
          "sha512": "66d9f743117ea67460cf234d683369bc4f500d0f03bafd616b30aa1c6344779d3919b928b6ff05b1be2570d4d537d8959b6f1694e342f5bc76ae19e7d454d9cc",
          "sha256": "9b39b26f4b2eb0eea1cc8e80d9cd2cd8b84ed6f3faf74dc04ba221a5f3330882",
          "sha1": "ec387220287bcba0d005cc8a9d341db3924ed8bd",
          "md5": "c9b0c06827ccc7aaa5202633770cceb7"
        }
      ]
    }
  ]
}
