{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libFBaseUtils",
    "version": "1.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0-alpha02"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-crashlytics-buildtools",
          "version": {
            "requires": "2.8.1"
          }
        }
      ],
      "files": [
        {
          "name": "libFBaseUtils-1.9.aar",
          "url": "libFBaseUtils-1.9.aar",
          "size": 107250,
          "sha512": "21b8bccde2a1237bda400f0f40ed1a29a5fe38b894cc7c9a06cd4fafd394a82bb6dff2688d2ac5c0908c16b2ef3d604a2a83744b31c2cfb53f3de3669c4bd930",
          "sha256": "3c2fe4c46211ac5e98dcca7cb329f63b6bc0cd17bc96914387b571943b2533bd",
          "sha1": "0363cec4545f139727315bdebc7fa954e3a7e1e0",
          "md5": "f4ea894a2deee55d3810e933b0e52725"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.zhuchao.android",
          "module": "libEventInterface",
          "version": {
            "requires": "1.6"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.0-alpha01"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0-alpha02"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-crashlytics-buildtools",
          "version": {
            "requires": "2.8.1"
          }
        }
      ],
      "files": [
        {
          "name": "libFBaseUtils-1.9.aar",
          "url": "libFBaseUtils-1.9.aar",
          "size": 107250,
          "sha512": "21b8bccde2a1237bda400f0f40ed1a29a5fe38b894cc7c9a06cd4fafd394a82bb6dff2688d2ac5c0908c16b2ef3d604a2a83744b31c2cfb53f3de3669c4bd930",
          "sha256": "3c2fe4c46211ac5e98dcca7cb329f63b6bc0cd17bc96914387b571943b2533bd",
          "sha1": "0363cec4545f139727315bdebc7fa954e3a7e1e0",
          "md5": "f4ea894a2deee55d3810e933b0e52725"
        }
      ]
    }
  ]
}
