{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libFBaseUtils",
    "version": "1.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0-alpha02"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-crashlytics-buildtools",
          "version": {
            "requires": "2.8.1"
          }
        }
      ],
      "files": [
        {
          "name": "libFBaseUtils-1.9.aar",
          "url": "libFBaseUtils-1.9.aar",
          "size": 111747,
          "sha512": "0b723663a6d8a1b6d7f23f018b6ffab61fb8f18071b7b631417065c230bfb9dfc3405354dbf6d53af046fdc3e983fbb1b5a2fa5aabb0632bc85a831508c09bce",
          "sha256": "6b1a8228c4a44475fe57b1618ef89f54416551de1452720c1e355f8a472bdc61",
          "sha1": "38bcb237bb21f36c2aa7266ffa6c2cb6b41ad10c",
          "md5": "539646d97f9b9f05b8025fef02e41437"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.zhuchao.android",
          "module": "libEventInterface",
          "version": {
            "requires": "1.6"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.0-alpha01"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0-alpha02"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-crashlytics-buildtools",
          "version": {
            "requires": "2.8.1"
          }
        }
      ],
      "files": [
        {
          "name": "libFBaseUtils-1.9.aar",
          "url": "libFBaseUtils-1.9.aar",
          "size": 111747,
          "sha512": "0b723663a6d8a1b6d7f23f018b6ffab61fb8f18071b7b631417065c230bfb9dfc3405354dbf6d53af046fdc3e983fbb1b5a2fa5aabb0632bc85a831508c09bce",
          "sha256": "6b1a8228c4a44475fe57b1618ef89f54416551de1452720c1e355f8a472bdc61",
          "sha1": "38bcb237bb21f36c2aa7266ffa6c2cb6b41ad10c",
          "md5": "539646d97f9b9f05b8025fef02e41437"
        }
      ]
    }
  ]
}
