{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libFBaseUtils",
    "version": "1.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0-alpha02"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "libFBaseUtils-1.9.aar",
          "url": "libFBaseUtils-1.9.aar",
          "size": 105808,
          "sha512": "cf62a9aa2e1d9a3cd05cd90f71abbd3aabde0652cd8c92c154843b016d3b6ad4b23ce42616ed07e072d40115d5a8018eea986fe568a0819db3a15d5c35904441",
          "sha256": "45a4932877bf0a67a3614a51ad346f9bf861b18440f25c37aa3127d0e14d95ba",
          "sha1": "6d79a22ae28b09c538845005ddae5d6af28de86f",
          "md5": "b6aa74e23e98f3a85d37d505b6862ad1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.zhuchao.android",
          "module": "libEventInterface",
          "version": {
            "requires": "1.6"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.0-alpha01"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0-alpha02"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "libFBaseUtils-1.9.aar",
          "url": "libFBaseUtils-1.9.aar",
          "size": 105808,
          "sha512": "cf62a9aa2e1d9a3cd05cd90f71abbd3aabde0652cd8c92c154843b016d3b6ad4b23ce42616ed07e072d40115d5a8018eea986fe568a0819db3a15d5c35904441",
          "sha256": "45a4932877bf0a67a3614a51ad346f9bf861b18440f25c37aa3127d0e14d95ba",
          "sha1": "6d79a22ae28b09c538845005ddae5d6af28de86f",
          "md5": "b6aa74e23e98f3a85d37d505b6862ad1"
        }
      ]
    }
  ]
}
