{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libMediaUtils",
    "version": "1.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libMediaUtils-1.7.aar",
          "url": "libMediaUtils-1.7.aar",
          "size": 32841,
          "sha512": "4764c87d35f36981244f0071d409211b95de7b5754167dbd3e0e3dca816fc30110ece6d6715fed4fcf61a897d717ab4228e286c308c594ba739ae6b3164fca6b",
          "sha256": "b5afef8026dd726aa8bca6ac6a96df8a8d24d006f6e928ab7934767a367ec4ab",
          "sha1": "c6ca5fbf31f62545c7f257b38ea165378da77b0f",
          "md5": "12ec7f650b5b7da213879f0050c360cc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.zhuchao.android",
          "module": "libEventInterface",
          "version": {
            "requires": "1.6"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libFBaseUtils",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libGPersistUtils",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libINetUtils",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libJOSUtils",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libPlayerUtils",
          "version": {
            "requires": "2.6"
          }
        }
      ],
      "files": [
        {
          "name": "libMediaUtils-1.7.aar",
          "url": "libMediaUtils-1.7.aar",
          "size": 32841,
          "sha512": "4764c87d35f36981244f0071d409211b95de7b5754167dbd3e0e3dca816fc30110ece6d6715fed4fcf61a897d717ab4228e286c308c594ba739ae6b3164fca6b",
          "sha256": "b5afef8026dd726aa8bca6ac6a96df8a8d24d006f6e928ab7934767a367ec4ab",
          "sha1": "c6ca5fbf31f62545c7f257b38ea165378da77b0f",
          "md5": "12ec7f650b5b7da213879f0050c360cc"
        }
      ]
    }
  ]
}
