{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libMediaUtils",
    "version": "1.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libMediaUtils-1.7.aar",
          "url": "libMediaUtils-1.7.aar",
          "size": 31354,
          "sha512": "9e1cf5fdc621467b9ad06e68a84f9cdbdbda35121f522969d1ff7f125662b2a79515ddca639d4f45d36e95400c1308cdebe3ab1d936bbe6d99a500a5ac64d85d",
          "sha256": "f6e7610e3abc93eff20db3a07ca42e0135a82b5be8f82ddfe97ccefe10037c0c",
          "sha1": "aeaab72c23895089047d174fe35a88f8e923e779",
          "md5": "815421a2426b83e0cb8e88637e667835"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.zhuchao.android",
          "module": "libEventInterface",
          "version": {
            "requires": "1.6"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libFBaseUitls",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libGPersistUtils",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libINetUtils",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libJOSUtils",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libPlayerUtils",
          "version": {
            "requires": "2.6"
          }
        }
      ],
      "files": [
        {
          "name": "libMediaUtils-1.7.aar",
          "url": "libMediaUtils-1.7.aar",
          "size": 31354,
          "sha512": "9e1cf5fdc621467b9ad06e68a84f9cdbdbda35121f522969d1ff7f125662b2a79515ddca639d4f45d36e95400c1308cdebe3ab1d936bbe6d99a500a5ac64d85d",
          "sha256": "f6e7610e3abc93eff20db3a07ca42e0135a82b5be8f82ddfe97ccefe10037c0c",
          "sha1": "aeaab72c23895089047d174fe35a88f8e923e779",
          "md5": "815421a2426b83e0cb8e88637e667835"
        }
      ]
    }
  ]
}
