{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libMediaUtils",
    "version": "1.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libMediaUtils-1.7.aar",
          "url": "libMediaUtils-1.7.aar",
          "size": 29275,
          "sha512": "46578e4577a44ab34043faef7677766d2338a3323ca1b6fd4db4b9ad3bd9dee033dc003990bdd103a62cfc633287e926d3780f897db904d4759f8efe5ec63557",
          "sha256": "d6264c9cb0e8d844a95b78bea7b9e4c4560eb9673ea0fc9be848461445802022",
          "sha1": "5f7f67544807489e470ba50bdd6773af5ff06005",
          "md5": "411812304d6efc7d4b45d7b839f482cd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.zhuchao.android",
          "module": "libEventInterface",
          "version": {
            "requires": "1.5"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libFileUtils",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libGPersistUtils",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libINetUtils",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libJOSUtils",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libPlayerUtils",
          "version": {
            "requires": "2.6"
          }
        }
      ],
      "files": [
        {
          "name": "libMediaUtils-1.7.aar",
          "url": "libMediaUtils-1.7.aar",
          "size": 29275,
          "sha512": "46578e4577a44ab34043faef7677766d2338a3323ca1b6fd4db4b9ad3bd9dee033dc003990bdd103a62cfc633287e926d3780f897db904d4759f8efe5ec63557",
          "sha256": "d6264c9cb0e8d844a95b78bea7b9e4c4560eb9673ea0fc9be848461445802022",
          "sha1": "5f7f67544807489e470ba50bdd6773af5ff06005",
          "md5": "411812304d6efc7d4b45d7b839f482cd"
        }
      ]
    }
  ]
}
