{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libFOSUtils",
    "version": "1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libFOSUtils-1.4.aar",
          "url": "libFOSUtils-1.4.aar",
          "size": 166375,
          "sha512": "4e6ef566c292a9b8663d1629a14547a62d85b1b1a90a3078416df1749f5ed892c59ea25967c5b9226bb6fd8685d39ab616e46b978c7ea36258cb202646680c87",
          "sha256": "e60c276c4f3af5b02d3d25574489b5b3359d9fb1787ad0a1051f0fd102dadc35",
          "sha1": "d6a79562e1defa73d8640654e12c70067c886a21",
          "md5": "3e2720b160d6939e631ecf71ceca0cfc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.zhuchao.android",
          "module": "libBaseUtils",
          "version": {
            "requires": "2.2"
          }
        }
      ],
      "files": [
        {
          "name": "libFOSUtils-1.4.aar",
          "url": "libFOSUtils-1.4.aar",
          "size": 166375,
          "sha512": "4e6ef566c292a9b8663d1629a14547a62d85b1b1a90a3078416df1749f5ed892c59ea25967c5b9226bb6fd8685d39ab616e46b978c7ea36258cb202646680c87",
          "sha256": "e60c276c4f3af5b02d3d25574489b5b3359d9fb1787ad0a1051f0fd102dadc35",
          "sha1": "d6a79562e1defa73d8640654e12c70067c886a21",
          "md5": "3e2720b160d6939e631ecf71ceca0cfc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "libFOSUtils-1.4-sources.jar",
          "url": "libFOSUtils-1.4-sources.jar",
          "size": 71100,
          "sha512": "f9f6ffa24b93124a303663e58e880bffbff0666a536b381bb40c463f32bb6feecf0468b36763e99647ba2b1dfbec5a036cf22b03151a8c11070736dfd5f44fa3",
          "sha256": "f3ec52f7dbe0e9c81a27a978820a7fa6d213395c112c5dcd10c79b06a7e9497a",
          "sha1": "0215b4171182900f6e47a3ea1bfb18c6527e4ab1",
          "md5": "88e79b4fdb73f2dc2d3c595ec13de70c"
        }
      ]
    }
  ]
}
