{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libFOSUtils",
    "version": "1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libFOSUtils-1.4.aar",
          "url": "libFOSUtils-1.4.aar",
          "size": 166399,
          "sha512": "b4568ba4788bca4081d2f44804e1745f9655aed6865817e2ab70e3ea83368367c56b46bdceaab8b07e7d17be9a655d7729a6196c2f39f42bf7f096cbb3cf3129",
          "sha256": "4083cbe3078765bfa05be54fdeeaecdb4f364656efbad76c7cb51232080601e8",
          "sha1": "db086110732d27ccfbfc5a90db675c0f92fe68ab",
          "md5": "49da4fe0479b8916bc56b4e48e6ede83"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.zhuchao.android",
          "module": "libBaseUtils",
          "version": {
            "requires": "2.2"
          }
        }
      ],
      "files": [
        {
          "name": "libFOSUtils-1.4.aar",
          "url": "libFOSUtils-1.4.aar",
          "size": 166399,
          "sha512": "b4568ba4788bca4081d2f44804e1745f9655aed6865817e2ab70e3ea83368367c56b46bdceaab8b07e7d17be9a655d7729a6196c2f39f42bf7f096cbb3cf3129",
          "sha256": "4083cbe3078765bfa05be54fdeeaecdb4f364656efbad76c7cb51232080601e8",
          "sha1": "db086110732d27ccfbfc5a90db675c0f92fe68ab",
          "md5": "49da4fe0479b8916bc56b4e48e6ede83"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "libFOSUtils-1.4-sources.jar",
          "url": "libFOSUtils-1.4-sources.jar",
          "size": 71126,
          "sha512": "ac6d600c78b167c4b7dc3143ab18a9e142c79f06c22ab63c920f76310ad8d30cddc274eee7da523f65cd55bc9c026f6f1774ca9b1bd76fbdccc4b5217317ebde",
          "sha256": "7dbb4269ce6956dad645335ecb6c687253f6d81cf009b87defd0a7eaab01fca9",
          "sha1": "ba6f75f9cf70a130b80a96581cc509727da658e3",
          "md5": "507674349fef13ec19f6a94e358add68"
        }
      ]
    }
  ]
}
