{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libJOSUtils",
    "version": "1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libJOSUtils-1.4.aar",
          "url": "libJOSUtils-1.4.aar",
          "size": 235501,
          "sha512": "becf79cf3713a34d7f7b3654fabc532cd7444ad01552bd81b9a71c142e73404f047f6132e10f324ea43033161824ef72cf9c8c3cf1d4e26dba076825eb30b3eb",
          "sha256": "8fcf9ac4b79b41873b8ff60183324cbe67568e565f18121f3a2f743bad0120ca",
          "sha1": "624f551d8e9f88a611ab24a60dddac14faa65db9",
          "md5": "eecab2374b42fec0af7be28a3809f87f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.zhuchao.android",
          "module": "libFBaseUtils",
          "version": {
            "requires": "2.1"
          }
        }
      ],
      "files": [
        {
          "name": "libJOSUtils-1.4.aar",
          "url": "libJOSUtils-1.4.aar",
          "size": 235501,
          "sha512": "becf79cf3713a34d7f7b3654fabc532cd7444ad01552bd81b9a71c142e73404f047f6132e10f324ea43033161824ef72cf9c8c3cf1d4e26dba076825eb30b3eb",
          "sha256": "8fcf9ac4b79b41873b8ff60183324cbe67568e565f18121f3a2f743bad0120ca",
          "sha1": "624f551d8e9f88a611ab24a60dddac14faa65db9",
          "md5": "eecab2374b42fec0af7be28a3809f87f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "libJOSUtils-1.4-sources.jar",
          "url": "libJOSUtils-1.4-sources.jar",
          "size": 137213,
          "sha512": "5582288b1b80db2e4b2dc85213bdcac58cd525edf5547dbe08e34c7b0cc59325257830ab6f0f01c0b11856fd734079a9adce718dfb23ce53cd1bd981301c1655",
          "sha256": "238d8336eccfa3135874f0036025a31c4a18b1b08ac61a5eb9f5afa6bf1aa7b6",
          "sha1": "bccadd7d422769a407f99c4709c5441941c914d2",
          "md5": "98a6e91bd4a15f0b0c2b555ca4ced5c7"
        }
      ]
    }
  ]
}
