{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libJOSUtils",
    "version": "1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libJOSUtils-1.4.aar",
          "url": "libJOSUtils-1.4.aar",
          "size": 235630,
          "sha512": "08e23da30c18b081957b8cae7ac9d6a5c0a51bee7654f1c799847ab3922c49e56d781970b4a2087ae37121b0ec5ce66c18485062b71d557d807a7c2a595afdb9",
          "sha256": "c163be93dab0f452812f80f8cc4c7ecddd11d72aef74230f60ffbe8ef4d05073",
          "sha1": "895aa888dde80d3860f482f39828399f2a04e999",
          "md5": "2721c3931e48957ad8ae8d6052a5c86f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.zhuchao.android",
          "module": "libFBaseUtils",
          "version": {
            "requires": "2.1"
          }
        }
      ],
      "files": [
        {
          "name": "libJOSUtils-1.4.aar",
          "url": "libJOSUtils-1.4.aar",
          "size": 235630,
          "sha512": "08e23da30c18b081957b8cae7ac9d6a5c0a51bee7654f1c799847ab3922c49e56d781970b4a2087ae37121b0ec5ce66c18485062b71d557d807a7c2a595afdb9",
          "sha256": "c163be93dab0f452812f80f8cc4c7ecddd11d72aef74230f60ffbe8ef4d05073",
          "sha1": "895aa888dde80d3860f482f39828399f2a04e999",
          "md5": "2721c3931e48957ad8ae8d6052a5c86f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "libJOSUtils-1.4-sources.jar",
          "url": "libJOSUtils-1.4-sources.jar",
          "size": 137271,
          "sha512": "268dc7204e829cf1396ab5e74abbff86c9a90365e45d491070f1b8216d4f7688a4b72039f230a357c1c4bfecb78ca00741e8549c04f1af37e7a725144c8452f7",
          "sha256": "fbc818472dfd80a61fc6982b8de37772c44997b5981b1502ade0148109f992e0",
          "sha1": "be5f7bbc225beb632a316a8c7bd5e36568b95115",
          "md5": "db93c866b0d6f97ac29c288e58737ba8"
        }
      ]
    }
  ]
}
