{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libJOSUtils",
    "version": "1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libJOSUtils-1.2.aar",
          "url": "libJOSUtils-1.2.aar",
          "size": 51476,
          "sha512": "a9111ef97e21d90568df337ccfb87220b0c5ef6e26b874b78b7df4a6b557419503bc04ebdfd64345b6b5f5346f4cf6f69e50e76afced96dc8ff0358c67728d97",
          "sha256": "654bba07b0370b3bab038039168c76856ca425fb1b7cc5d8f2af6988aa8552dc",
          "sha1": "55c90ed767df3a02ddaaf63b147dc69863118c74",
          "md5": "069b920d189e0a68fd54f7b9d8e355e4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.zhuchao.android",
          "module": "libCallbackEvent",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libFileUtils",
          "version": {
            "requires": "1.7"
          }
        }
      ],
      "files": [
        {
          "name": "libJOSUtils-1.2.aar",
          "url": "libJOSUtils-1.2.aar",
          "size": 51476,
          "sha512": "a9111ef97e21d90568df337ccfb87220b0c5ef6e26b874b78b7df4a6b557419503bc04ebdfd64345b6b5f5346f4cf6f69e50e76afced96dc8ff0358c67728d97",
          "sha256": "654bba07b0370b3bab038039168c76856ca425fb1b7cc5d8f2af6988aa8552dc",
          "sha1": "55c90ed767df3a02ddaaf63b147dc69863118c74",
          "md5": "069b920d189e0a68fd54f7b9d8e355e4"
        }
      ]
    }
  ]
}
