{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libJOSUtils",
    "version": "1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libJOSUtils-1.2.aar",
          "url": "libJOSUtils-1.2.aar",
          "size": 52951,
          "sha512": "5032684e64a77f1a3c034c13826729549b037aaa17ed7daf48504f6d9643705a173906a1644bf9818b849d20390e8c0f1ac6d336319ccd8ddc58a3a5445f5c51",
          "sha256": "e58518fd4c452ffa53660573cf2969140b46842f599f9ccef48b3fc0e98f67ed",
          "sha1": "86bdd0195d445f7601f1f0a4a3d7610fd0f2a4ac",
          "md5": "64aff424253dea76f213cb7688f02b9e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.zhuchao.android",
          "module": "libEventInterface",
          "version": {
            "requires": "1.6"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libFBaseUtils",
          "version": {
            "requires": "1.8"
          }
        }
      ],
      "files": [
        {
          "name": "libJOSUtils-1.2.aar",
          "url": "libJOSUtils-1.2.aar",
          "size": 52951,
          "sha512": "5032684e64a77f1a3c034c13826729549b037aaa17ed7daf48504f6d9643705a173906a1644bf9818b849d20390e8c0f1ac6d336319ccd8ddc58a3a5445f5c51",
          "sha256": "e58518fd4c452ffa53660573cf2969140b46842f599f9ccef48b3fc0e98f67ed",
          "sha1": "86bdd0195d445f7601f1f0a4a3d7610fd0f2a4ac",
          "md5": "64aff424253dea76f213cb7688f02b9e"
        }
      ]
    }
  ]
}
