{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libJOSUtils",
    "version": "1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libJOSUtils-1.2.aar",
          "url": "libJOSUtils-1.2.aar",
          "size": 52524,
          "sha512": "7a9654046722efc53a7724fc9e7775600c8849b1f1ceed7bf24401375b4a595a6d36d20dd049fc3eec6ddc295c2cedd77f792d2e26d749c0f43f447fbefc4903",
          "sha256": "5aa6b612dacd92acc590cb5067978ece45ed5609187c8d9c1e560544c62ebe35",
          "sha1": "f44befcbd1018eac576528ce93154461db0e329a",
          "md5": "ff72cc9e30dc59822fcbb343a53fef1a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.zhuchao.android",
          "module": "libEventInterface",
          "version": {
            "requires": "1.6"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libFBaseUitls",
          "version": {
            "requires": "1.8"
          }
        }
      ],
      "files": [
        {
          "name": "libJOSUtils-1.2.aar",
          "url": "libJOSUtils-1.2.aar",
          "size": 52524,
          "sha512": "7a9654046722efc53a7724fc9e7775600c8849b1f1ceed7bf24401375b4a595a6d36d20dd049fc3eec6ddc295c2cedd77f792d2e26d749c0f43f447fbefc4903",
          "sha256": "5aa6b612dacd92acc590cb5067978ece45ed5609187c8d9c1e560544c62ebe35",
          "sha1": "f44befcbd1018eac576528ce93154461db0e329a",
          "md5": "ff72cc9e30dc59822fcbb343a53fef1a"
        }
      ]
    }
  ]
}
