{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libMediaUtils",
    "version": "1.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libMediaUtils-1.8.aar",
          "url": "libMediaUtils-1.8.aar",
          "size": 33648,
          "sha512": "3ae853ef33cfc19f8a98a3c5c9608029abc85ad3982e992fd410ba96f3cd56195fabffdbb1e5f928c33a2efe8cafeb2493f4310d14b8e49021d0d442145d4989",
          "sha256": "50796e026be00caca39e61de137a3239b584958b8d7999ef400bdd53db94194e",
          "sha1": "f1877cebc98a258175c32d5dc5fcfac5ed9fcde5",
          "md5": "7e304f78ff597c1a752215fc501f6472"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.zhuchao.android",
          "module": "libEventInterface",
          "version": {
            "requires": "1.6"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libFBaseUtils",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libGPersistUtils",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libINetUtils",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libJOSUtils",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libPlayerUtils",
          "version": {
            "requires": "2.7"
          }
        }
      ],
      "files": [
        {
          "name": "libMediaUtils-1.8.aar",
          "url": "libMediaUtils-1.8.aar",
          "size": 33648,
          "sha512": "3ae853ef33cfc19f8a98a3c5c9608029abc85ad3982e992fd410ba96f3cd56195fabffdbb1e5f928c33a2efe8cafeb2493f4310d14b8e49021d0d442145d4989",
          "sha256": "50796e026be00caca39e61de137a3239b584958b8d7999ef400bdd53db94194e",
          "sha1": "f1877cebc98a258175c32d5dc5fcfac5ed9fcde5",
          "md5": "7e304f78ff597c1a752215fc501f6472"
        }
      ]
    }
  ]
}
