{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libMediaUtils",
    "version": "1.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libMediaUtils-1.8.aar",
          "url": "libMediaUtils-1.8.aar",
          "size": 20827,
          "sha512": "dc53ce3c013f108d851bf3b24f95e266fb9f9a9f82d26aef56401f3437c8bdb335a2d3f0ac9911252c07dd488f5719ada5943cbe8617d8762125b1896e332c5a",
          "sha256": "827b05028a8d55f7a7e369b8330adb40f09999a1e01c34db1383e8299047ad45",
          "sha1": "7320dc03c2f4f4912cdb28260973d0ec3054821d",
          "md5": "c614190c626765d77dd286f9c0a3c348"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.zhuchao.android",
          "module": "libFBaseUtils",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libGPersistUtils",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libINetUtils",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libJOSUtils",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libPlayerUtils",
          "version": {
            "requires": "2.8"
          }
        }
      ],
      "files": [
        {
          "name": "libMediaUtils-1.8.aar",
          "url": "libMediaUtils-1.8.aar",
          "size": 20827,
          "sha512": "dc53ce3c013f108d851bf3b24f95e266fb9f9a9f82d26aef56401f3437c8bdb335a2d3f0ac9911252c07dd488f5719ada5943cbe8617d8762125b1896e332c5a",
          "sha256": "827b05028a8d55f7a7e369b8330adb40f09999a1e01c34db1383e8299047ad45",
          "sha1": "7320dc03c2f4f4912cdb28260973d0ec3054821d",
          "md5": "c614190c626765d77dd286f9c0a3c348"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "libMediaUtils-1.8-sources.jar",
          "url": "libMediaUtils-1.8-sources.jar",
          "size": 10849,
          "sha512": "5622b6f0bd814909b2775e350c791270536ba890bb96faf519b52e6c8666f29a7184b72fc6571821d7a00f392762ce78943a6543c7a48533550e6dff2e56e2b8",
          "sha256": "2eef7f379a98128c35479abccbc50d5957c836f99afdd9023d22d00453e36bdf",
          "sha1": "4b6d120e394c6ac52d5bc6050d6aa088b87a0334",
          "md5": "c6b3579b79657f1d4c68e0ba7966d5cb"
        }
      ]
    }
  ]
}
