{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libMediaUtils",
    "version": "1.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libMediaUtils-1.8.aar",
          "url": "libMediaUtils-1.8.aar",
          "size": 20946,
          "sha512": "1fed5594049a6e762b05fad7f5c215a6710af34cdea011b2ae5ace5ab3c7ab5f76c8b671dddc5155b243b74ef56bb1a7d547cb0bd2ab8dc1e39d730b2c1654bf",
          "sha256": "46082192d1514fb295027f5a1ff9085def2ae74c68ca6a4e512b5fc6c0c15f95",
          "sha1": "b3302b154b7ff2d2418cc8a1c8de7f5a3e41ace3",
          "md5": "db0b895cb3cee0018bf2badbcca86a1c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.zhuchao.android",
          "module": "libFBaseUtils",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libGPersistUtils",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libINetUtils",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libJOSUtils",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libPlayerUtils",
          "version": {
            "requires": "2.8"
          }
        }
      ],
      "files": [
        {
          "name": "libMediaUtils-1.8.aar",
          "url": "libMediaUtils-1.8.aar",
          "size": 20946,
          "sha512": "1fed5594049a6e762b05fad7f5c215a6710af34cdea011b2ae5ace5ab3c7ab5f76c8b671dddc5155b243b74ef56bb1a7d547cb0bd2ab8dc1e39d730b2c1654bf",
          "sha256": "46082192d1514fb295027f5a1ff9085def2ae74c68ca6a4e512b5fc6c0c15f95",
          "sha1": "b3302b154b7ff2d2418cc8a1c8de7f5a3e41ace3",
          "md5": "db0b895cb3cee0018bf2badbcca86a1c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "libMediaUtils-1.8-sources.jar",
          "url": "libMediaUtils-1.8-sources.jar",
          "size": 10865,
          "sha512": "8b803621176b5ed68f47f4d566b83ccba485154e85d4973ee97d3c0550228e53d52001c3cc6a53e2792b705caa7d19f3b50a5fc36f5225a2185cbd77ff3474ba",
          "sha256": "e40c0bc024606632da6c4c229598a091292c953a2df156c6ca52c89551768cea",
          "sha1": "43a73d62a9d377f35517856a94e6edba4642038b",
          "md5": "a0014b0c2750c34e937edcb47bca0caf"
        }
      ]
    }
  ]
}
