{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libFileUtils",
    "version": "1.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0-alpha02"
          }
        }
      ],
      "files": [
        {
          "name": "libFileUtils-1.7.aar",
          "url": "libFileUtils-1.7.aar",
          "size": 75936,
          "sha512": "02a5d84738fafd8fc1ece9148cef98c4b5177ae70c026e57e739ff210215821e5edebc5c17255a4d642ea148d1731e167417863a1790389676ff6e1f9a86d8f1",
          "sha256": "72fbb8553b9cd24f9f542b36200ad79cc3b14a6fac249c016c0bfcfc03ef5d27",
          "sha1": "6d07fe945aa0b410e796a45ea10f24fde988e9ac",
          "md5": "037eb9100a3006c74b727624b19ea8f3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.zhuchao.android",
          "module": "libCallbackEvent",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.0-alpha01"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0-alpha02"
          }
        }
      ],
      "files": [
        {
          "name": "libFileUtils-1.7.aar",
          "url": "libFileUtils-1.7.aar",
          "size": 75936,
          "sha512": "02a5d84738fafd8fc1ece9148cef98c4b5177ae70c026e57e739ff210215821e5edebc5c17255a4d642ea148d1731e167417863a1790389676ff6e1f9a86d8f1",
          "sha256": "72fbb8553b9cd24f9f542b36200ad79cc3b14a6fac249c016c0bfcfc03ef5d27",
          "sha1": "6d07fe945aa0b410e796a45ea10f24fde988e9ac",
          "md5": "037eb9100a3006c74b727624b19ea8f3"
        }
      ]
    }
  ]
}
