{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libFileUtils",
    "version": "1.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0-alpha02"
          }
        }
      ],
      "files": [
        {
          "name": "libFileUtils-1.7.aar",
          "url": "libFileUtils-1.7.aar",
          "size": 76031,
          "sha512": "2983e1aa383c8da244cfb81c3066fe26f3fc15f3f9c806a03937a5bd736c14bbd0227ce176b2b9d8d40d67e18e5f2d77f9b78716fe70a894ebf640e586dcaafd",
          "sha256": "20c61d5b71dbc7f9451a594611725f3b4aa2b18234bcd0e407bbf730e93f9a8a",
          "sha1": "32cfd54c9bd33122a73123da40d7015955cdf331",
          "md5": "4f8a2189c0e35c4a61a7ab25b2d17415"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.zhuchao.android",
          "module": "libEventInterface",
          "version": {
            "requires": "1.5"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.0-alpha01"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0-alpha02"
          }
        }
      ],
      "files": [
        {
          "name": "libFileUtils-1.7.aar",
          "url": "libFileUtils-1.7.aar",
          "size": 76031,
          "sha512": "2983e1aa383c8da244cfb81c3066fe26f3fc15f3f9c806a03937a5bd736c14bbd0227ce176b2b9d8d40d67e18e5f2d77f9b78716fe70a894ebf640e586dcaafd",
          "sha256": "20c61d5b71dbc7f9451a594611725f3b4aa2b18234bcd0e407bbf730e93f9a8a",
          "sha1": "32cfd54c9bd33122a73123da40d7015955cdf331",
          "md5": "4f8a2189c0e35c4a61a7ab25b2d17415"
        }
      ]
    }
  ]
}
