{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libFileUtils",
    "version": "1.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0-alpha02"
          }
        }
      ],
      "files": [
        {
          "name": "libFileUtils-1.7.aar",
          "url": "libFileUtils-1.7.aar",
          "size": 79159,
          "sha512": "8c26fc223e79ff85412f6b0f9740caab262986077a2403b9bd9c57df3069a02f6fa0838044e408e29fe678b18e29f1d2aaee786754676b52eab3903bafead023",
          "sha256": "28254a4cb181b482c4ec2b7b76a5e3125d680e3a40093c4ffe3a2115796b63e5",
          "sha1": "fb58201c773e8a55f53c58827ca36bf1eaad2ef0",
          "md5": "402ca33687d3b081b35a82c9f41d08dd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.zhuchao.android",
          "module": "libEventInterface",
          "version": {
            "requires": "1.5"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.0-alpha01"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0-alpha02"
          }
        }
      ],
      "files": [
        {
          "name": "libFileUtils-1.7.aar",
          "url": "libFileUtils-1.7.aar",
          "size": 79159,
          "sha512": "8c26fc223e79ff85412f6b0f9740caab262986077a2403b9bd9c57df3069a02f6fa0838044e408e29fe678b18e29f1d2aaee786754676b52eab3903bafead023",
          "sha256": "28254a4cb181b482c4ec2b7b76a5e3125d680e3a40093c4ffe3a2115796b63e5",
          "sha1": "fb58201c773e8a55f53c58827ca36bf1eaad2ef0",
          "md5": "402ca33687d3b081b35a82c9f41d08dd"
        }
      ]
    }
  ]
}
