{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libOSUtils",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libOSUtils-1.0.aar",
          "url": "libOSUtils-1.0.aar",
          "size": 33516,
          "sha512": "6acf2f9cd12ec6011833dc8db3e22ade7a3bce33d25ca8af0dff4cc9a0aeb52a04da1b60ed41d658c490d35e89aed65bd94dbe644f00c1e33451b5b9dd8e6621",
          "sha256": "0cbeb383336e49a9795959cf9bca82da5e5b98bb17747bd37ffaf48f60168825",
          "sha1": "60c3c34eb53bcef5ce2203dcaca200922a1fe3ad",
          "md5": "d804cf1406398f25ccc786d39992b916"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.zhuchao.android",
          "module": "libCallbackEvent",
          "version": {
            "requires": "1.2"
          }
        }
      ],
      "files": [
        {
          "name": "libOSUtils-1.0.aar",
          "url": "libOSUtils-1.0.aar",
          "size": 33516,
          "sha512": "6acf2f9cd12ec6011833dc8db3e22ade7a3bce33d25ca8af0dff4cc9a0aeb52a04da1b60ed41d658c490d35e89aed65bd94dbe644f00c1e33451b5b9dd8e6621",
          "sha256": "0cbeb383336e49a9795959cf9bca82da5e5b98bb17747bd37ffaf48f60168825",
          "sha1": "60c3c34eb53bcef5ce2203dcaca200922a1fe3ad",
          "md5": "d804cf1406398f25ccc786d39992b916"
        }
      ]
    }
  ]
}
