{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libOpenComputerVision",
    "version": "1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "libOpenComputerVision-1.1.aar",
          "url": "libOpenComputerVision-1.1.aar",
          "size": 30962203,
          "sha512": "e384cf8265c4305680cbc2550dd3965cc6ff0b8956d4dc60ed6bdb2eea6f3235ba8e0c92793e26d9572ac46885be1ab55d91834b861afa5db1912156c12f9ca9",
          "sha256": "4f1d0da4deaac70e85057e5438a2e70255287bf9c1f4290f340730b09bc9b743",
          "sha1": "d461a82ef7141b2605ee1ecec38c54373c6964aa",
          "md5": "05e226407b1db0ea1cf38d750eb99943"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "libOpenComputerVision-1.1.aar",
          "url": "libOpenComputerVision-1.1.aar",
          "size": 30962203,
          "sha512": "e384cf8265c4305680cbc2550dd3965cc6ff0b8956d4dc60ed6bdb2eea6f3235ba8e0c92793e26d9572ac46885be1ab55d91834b861afa5db1912156c12f9ca9",
          "sha256": "4f1d0da4deaac70e85057e5438a2e70255287bf9c1f4290f340730b09bc9b743",
          "sha1": "d461a82ef7141b2605ee1ecec38c54373c6964aa",
          "md5": "05e226407b1db0ea1cf38d750eb99943"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "libOpenComputerVision-1.1-sources.jar",
          "url": "libOpenComputerVision-1.1-sources.jar",
          "size": 681796,
          "sha512": "ae5fe258f183be9fecb178eb09329c3e20bd0506ed179862bb36b0b974009977f07545a60a93cd75aa5bff1cb403bdde8f243aefc3a31894f523e883e4ec4b77",
          "sha256": "f8c8bcb0aa8d4f9aeb9746d584aab8ade8ca81056ee015e20bbc0c25c1f9e736",
          "sha1": "0ee6f3b55429dfa4f7ea3b1e8565b6b4045a9240",
          "md5": "9e604ab64c942d9a2bbe920753d8f1d1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "libOpenComputerVision-1.1-javadoc.jar",
          "url": "libOpenComputerVision-1.1-javadoc.jar",
          "size": 2244424,
          "sha512": "eae585177159917713f659388b2b1ec30bd157e7f558b8445da00114df3fe9002788fc4d1669deeacffb99a6814d3fb2eb7230299b0bc7a25a8b4b0970e12aac",
          "sha256": "33b7a4e8469ea352bd75c1ae5ae38a12aa9b898922123fb64df5cc185ba726d5",
          "sha1": "9594fff062bb22a30b0b5c0e8c68a256d8d5f091",
          "md5": "2e059a92bdfa203d6a40daac1a63b8b1"
        }
      ]
    }
  ]
}
