{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libSessionUtils",
    "version": "2.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libSessionUtils-2.5.aar",
          "url": "libSessionUtils-2.5.aar",
          "size": 70628,
          "sha512": "51a43f29f51b6a0685291a54373640d1622d74d57d77f4d8702bb19511d2ee40d9bfee9b90419c95b39cbef0f3aab211d293d9c0a4c350c9e2cbee4d0d6dc97d",
          "sha256": "80456aec329d145de8d0509e45717dda0719e7359af73726ff3b9811a8283769",
          "sha1": "2c788ed50cd7ac3dd7c7afc0893a858ae956605b",
          "md5": "2baf9b456845046e9d51e4ff89f9b70c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.8"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libOSUtils",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libCallbackEvent",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libFileUtils",
          "version": {
            "requires": "1.5"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libNetUtils",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libMediaUtils",
          "version": {
            "requires": "1.5"
          }
        }
      ],
      "files": [
        {
          "name": "libSessionUtils-2.5.aar",
          "url": "libSessionUtils-2.5.aar",
          "size": 70628,
          "sha512": "51a43f29f51b6a0685291a54373640d1622d74d57d77f4d8702bb19511d2ee40d9bfee9b90419c95b39cbef0f3aab211d293d9c0a4c350c9e2cbee4d0d6dc97d",
          "sha256": "80456aec329d145de8d0509e45717dda0719e7359af73726ff3b9811a8283769",
          "sha1": "2c788ed50cd7ac3dd7c7afc0893a858ae956605b",
          "md5": "2baf9b456845046e9d51e4ff89f9b70c"
        }
      ]
    }
  ]
}
