{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libJOSUtils",
    "version": "1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libJOSUtils-1.1.aar",
          "url": "libJOSUtils-1.1.aar",
          "size": 55619,
          "sha512": "38cdc4504f19bcedc5ccccd55aca7e8d3a7344f2f5a1d4c78d7d218e157f40420d7ba7106c8af869852f06548ba637528334b4b318ce84a2e760c94f3f7351ff",
          "sha256": "b364b16f09b0b0b3fc4e0fb35ef2bfab2074b12a20b650d7cb586580c6d38978",
          "sha1": "c212d9a443e527798a18a6f549987778f3e24a97",
          "md5": "a75ed269f8bdae81739f4252c07e9f05"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.zhuchao.android",
          "module": "libCallbackEvent",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libFileUtils",
          "version": {
            "requires": "1.6"
          }
        }
      ],
      "files": [
        {
          "name": "libJOSUtils-1.1.aar",
          "url": "libJOSUtils-1.1.aar",
          "size": 55619,
          "sha512": "38cdc4504f19bcedc5ccccd55aca7e8d3a7344f2f5a1d4c78d7d218e157f40420d7ba7106c8af869852f06548ba637528334b4b318ce84a2e760c94f3f7351ff",
          "sha256": "b364b16f09b0b0b3fc4e0fb35ef2bfab2074b12a20b650d7cb586580c6d38978",
          "sha1": "c212d9a443e527798a18a6f549987778f3e24a97",
          "md5": "a75ed269f8bdae81739f4252c07e9f05"
        }
      ]
    }
  ]
}
