{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libJOSUtils",
    "version": "1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libJOSUtils-1.1.aar",
          "url": "libJOSUtils-1.1.aar",
          "size": 54664,
          "sha512": "99e8e541d3709f998113a16c110f8e1a9f33de7900eba8b3be421fc174dcb909d846d312cab347a918e165201f68ea63d2cba70e047c68149751671a610cb213",
          "sha256": "966b94efecd8c021f92c6000cde4b454a7662db14c7afbbe3dc677159f832f34",
          "sha1": "4e0770ae8de87381e8518e2b690e92c4fa2e4a12",
          "md5": "9bedfb48a16a0d928a44f99334fe8af9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.zhuchao.android",
          "module": "libCallbackEvent",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libFileUtils",
          "version": {
            "requires": "1.6"
          }
        }
      ],
      "files": [
        {
          "name": "libJOSUtils-1.1.aar",
          "url": "libJOSUtils-1.1.aar",
          "size": 54664,
          "sha512": "99e8e541d3709f998113a16c110f8e1a9f33de7900eba8b3be421fc174dcb909d846d312cab347a918e165201f68ea63d2cba70e047c68149751671a610cb213",
          "sha256": "966b94efecd8c021f92c6000cde4b454a7662db14c7afbbe3dc677159f832f34",
          "sha1": "4e0770ae8de87381e8518e2b690e92c4fa2e4a12",
          "md5": "9bedfb48a16a0d928a44f99334fe8af9"
        }
      ]
    }
  ]
}
