{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libOpenC-CNN",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libOpenC-CNN-1.0.aar",
          "url": "libOpenC-CNN-1.0.aar",
          "size": 123917,
          "sha512": "40c726426d589dcd6d2f743df435930417c8ac9b5fbdc9808413f7db4a25ec510295640cbcb8eb76437a434d95e5e7e75afe53bc853693633963dcab87b1c9f3",
          "sha256": "7337da7e9d2ed607a85b11eea43b54e694f852f92743f0e5cbba5ef27b1b15e5",
          "sha1": "63281ba1a8c1e6ab1a3528bb2cc855488c29c2f5",
          "md5": "457a0272ee000c4ad63ac229550d567c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "libOpenC-CNN-1.0.aar",
          "url": "libOpenC-CNN-1.0.aar",
          "size": 123917,
          "sha512": "40c726426d589dcd6d2f743df435930417c8ac9b5fbdc9808413f7db4a25ec510295640cbcb8eb76437a434d95e5e7e75afe53bc853693633963dcab87b1c9f3",
          "sha256": "7337da7e9d2ed607a85b11eea43b54e694f852f92743f0e5cbba5ef27b1b15e5",
          "sha1": "63281ba1a8c1e6ab1a3528bb2cc855488c29c2f5",
          "md5": "457a0272ee000c4ad63ac229550d567c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "libOpenC-CNN-1.0-sources.jar",
          "url": "libOpenC-CNN-1.0-sources.jar",
          "size": 1022,
          "sha512": "8eadc17a4854e8b5be93357fe2a590a649e2e9d71c4aa06b7726773c920c1bc878e635d13b3d6828f64eb1bf445f087629d589b80f8d3ca7c4ed4c638de9a4cf",
          "sha256": "6d87eee9b73eb18c413970078766fde1334960e7858a7b5350bb47cecc597901",
          "sha1": "8459b21af065a943369a8c77ffff1bae489bc099",
          "md5": "33ed9c3820e7ff275a672e26a9fb9e23"
        }
      ]
    }
  ]
}
