{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libEventInterface",
    "version": "1.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libEventInterface-1.6.aar",
          "url": "libEventInterface-1.6.aar",
          "size": 6038,
          "sha512": "7cfb2d2daebcc849ffeb50af21d23276e812938aa15803cf6fd10c0768ac2204b94e86156fdb14bd88e0cdf1d145379e025599519a27e3ae8b0a8c81e060709e",
          "sha256": "313aa0c8b933ba51cf3923e706d7f57b5ab063f50f4a0b5f7eb1d86e6b177629",
          "sha1": "dbcb73d8e912e0d541c16c724f6bc2f355082e14",
          "md5": "89333cdfa313a2e4c455471fc9c8df0b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "libEventInterface-1.6.aar",
          "url": "libEventInterface-1.6.aar",
          "size": 6038,
          "sha512": "7cfb2d2daebcc849ffeb50af21d23276e812938aa15803cf6fd10c0768ac2204b94e86156fdb14bd88e0cdf1d145379e025599519a27e3ae8b0a8c81e060709e",
          "sha256": "313aa0c8b933ba51cf3923e706d7f57b5ab063f50f4a0b5f7eb1d86e6b177629",
          "sha1": "dbcb73d8e912e0d541c16c724f6bc2f355082e14",
          "md5": "89333cdfa313a2e4c455471fc9c8df0b"
        }
      ]
    }
  ]
}
