{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libEventInterface",
    "version": "1.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libEventInterface-1.6.aar",
          "url": "libEventInterface-1.6.aar",
          "size": 6144,
          "sha512": "a1db290dc46d38f93eb2e087c9f37fcd26c02403963deab9bd405c271784301f1a4db7863e374fe4662be610c3e054ec72a96936638c93845e3344a5684d2892",
          "sha256": "6f2d9ca253fe60335d3b540a796ea95d62d68188adbad8c7ea8c36570f883fcd",
          "sha1": "d1dc674d6eaf83cd99d09ffe24aa1ce8765b236e",
          "md5": "c86001d40c869fd27ce535c7af1f2a93"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "libEventInterface-1.6.aar",
          "url": "libEventInterface-1.6.aar",
          "size": 6144,
          "sha512": "a1db290dc46d38f93eb2e087c9f37fcd26c02403963deab9bd405c271784301f1a4db7863e374fe4662be610c3e054ec72a96936638c93845e3344a5684d2892",
          "sha256": "6f2d9ca253fe60335d3b540a796ea95d62d68188adbad8c7ea8c36570f883fcd",
          "sha1": "d1dc674d6eaf83cd99d09ffe24aa1ce8765b236e",
          "md5": "c86001d40c869fd27ce535c7af1f2a93"
        }
      ]
    }
  ]
}
