{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libEventInterface",
    "version": "1.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libEventInterface-1.6.aar",
          "url": "libEventInterface-1.6.aar",
          "size": 6105,
          "sha512": "b1106c72e15f688d0909a10e0918a1c44092fbb1d3bca381d378e79128e2d6f7e00e05f44ea0eba343c41e16a1eb0ff3887f0324e484f0f4f73f04eb9dd6ba7c",
          "sha256": "c0e094aae65c75f3b0b8637f790f816042cb5dde181d61965a9271f927b3ba75",
          "sha1": "ec958783ec8553e4b14710942d8a3d7bfd8652d6",
          "md5": "3a962ea7b28efa3f9d47df9bf6cfc47d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "libEventInterface-1.6.aar",
          "url": "libEventInterface-1.6.aar",
          "size": 6105,
          "sha512": "b1106c72e15f688d0909a10e0918a1c44092fbb1d3bca381d378e79128e2d6f7e00e05f44ea0eba343c41e16a1eb0ff3887f0324e484f0f4f73f04eb9dd6ba7c",
          "sha256": "c0e094aae65c75f3b0b8637f790f816042cb5dde181d61965a9271f927b3ba75",
          "sha1": "ec958783ec8553e4b14710942d8a3d7bfd8652d6",
          "md5": "3a962ea7b28efa3f9d47df9bf6cfc47d"
        }
      ]
    }
  ]
}
