{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libC-CNN",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libC-CNN-0.1.aar",
          "url": "libC-CNN-0.1.aar",
          "size": 129061,
          "sha512": "5cb90c10a472c8ae127fc33bf498b5c0edc63049ed628d314a654323c1a5fd06620bd1ab95beb8bdca3771c61d4403cf45ecdfd50b0687b7be08f3fd87aad4e1",
          "sha256": "fa0330248b819dbfb1b53c75776f8e6ea5532f8444fd039daf57774eb2f54f9a",
          "sha1": "12d502aa94e6e9d174c99de48b05c7f82edb4f6a",
          "md5": "ba20a2f09ea8b90277012c149fb84dad"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "libC-CNN-0.1.aar",
          "url": "libC-CNN-0.1.aar",
          "size": 129061,
          "sha512": "5cb90c10a472c8ae127fc33bf498b5c0edc63049ed628d314a654323c1a5fd06620bd1ab95beb8bdca3771c61d4403cf45ecdfd50b0687b7be08f3fd87aad4e1",
          "sha256": "fa0330248b819dbfb1b53c75776f8e6ea5532f8444fd039daf57774eb2f54f9a",
          "sha1": "12d502aa94e6e9d174c99de48b05c7f82edb4f6a",
          "md5": "ba20a2f09ea8b90277012c149fb84dad"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "libC-CNN-0.1-sources.jar",
          "url": "libC-CNN-0.1-sources.jar",
          "size": 1027,
          "sha512": "cc070fb2c88bf2e38e4a8f1064219c8ba8db835f383fb4129674b700dd7ed875d36dbfbd432b8ce9f0e2d73b908d507724c71b413f35fcd42b3e050684d0300e",
          "sha256": "37a03f3dbfafd62c5c0d300f0aa8bafc80bca0804dce32f5984000cc35cd909d",
          "sha1": "a07bd466318ed3cbff57fe26ff0168aba35af7bd",
          "md5": "12d629ffe697bf886552762d6536cc3d"
        }
      ]
    }
  ]
}
