{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libSessionUtils",
    "version": "2.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libSessionUtils-2.8.aar",
          "url": "libSessionUtils-2.8.aar",
          "size": 105998,
          "sha512": "485c80887e1bb4df8cb2c0f4992b91f8a8b61fda4945444633e059eff891ac3db40ff0524ac145583075c722387b180858e2a802eafe7d5938828c0bc96712f0",
          "sha256": "7dd681732b20045e2bb9aa3656753a6b325085dcc5909c2a0cfd08147f7fa566",
          "sha1": "4857be9defa2bd2afc9b60b48fb1590b282e0d9f",
          "md5": "8c4d99f094adb691e599b3eeb2f699dd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.zhuchao.android",
          "module": "libFBaseUtils",
          "version": {
            "requires": "2.1"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libJOSUtils",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libINetUtils",
          "version": {
            "requires": "2.1"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libMediaUtils",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libPlayerUtils",
          "version": {
            "requires": "3.0"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libGPersistUtils",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "libSessionUtils-2.8.aar",
          "url": "libSessionUtils-2.8.aar",
          "size": 105998,
          "sha512": "485c80887e1bb4df8cb2c0f4992b91f8a8b61fda4945444633e059eff891ac3db40ff0524ac145583075c722387b180858e2a802eafe7d5938828c0bc96712f0",
          "sha256": "7dd681732b20045e2bb9aa3656753a6b325085dcc5909c2a0cfd08147f7fa566",
          "sha1": "4857be9defa2bd2afc9b60b48fb1590b282e0d9f",
          "md5": "8c4d99f094adb691e599b3eeb2f699dd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "libSessionUtils-2.8-sources.jar",
          "url": "libSessionUtils-2.8-sources.jar",
          "size": 40459,
          "sha512": "4174310caf47867e05aa3b05667b6ec73b01fbde96e7ff903268905918b3da7496c549ce99e94bd22cfd77c685b33a628045b037b11ecbb82d0567af2198b2b8",
          "sha256": "1a51dc12b24af6b85d29ad3a40c93717d78fe10d5202b593fe6a0f508a30d72a",
          "sha1": "b2dab50c0b0ab89db360e2594bbc54c816330aae",
          "md5": "99e1fad5d53eb3b04c9b9e81c8622dae"
        }
      ]
    }
  ]
}
