{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libSessionUtils",
    "version": "2.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libSessionUtils-2.9.aar",
          "url": "libSessionUtils-2.9.aar",
          "size": 160632,
          "sha512": "23769347640bbe4531c5bc9d6cf550bb22ec1daa85ac29be14f500b25bd3b365f01bd0cb8b0251e852e17de42cb75cd494aea0c9bd34a3144fd41f37b8e7b2ff",
          "sha256": "cd7d7753aa26d60e7f0e8886b1684752f39e02f6ac3a0af375f0b2937c8e6e78",
          "sha1": "fb6444e3e37859eab9efc9cdf6cbdc5eafe7a030",
          "md5": "e57871508bb4a688c7b3a4cc43948555"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.media",
          "module": "media",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libBaseUtils",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libFOSUtils",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libDNetUtils",
          "version": {
            "requires": "2.1"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libGXMediaUtils",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libGXPlayerUtils",
          "version": {
            "requires": "3.0"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libFPersistUtils",
          "version": {
            "requires": "1.2"
          }
        }
      ],
      "files": [
        {
          "name": "libSessionUtils-2.9.aar",
          "url": "libSessionUtils-2.9.aar",
          "size": 160632,
          "sha512": "23769347640bbe4531c5bc9d6cf550bb22ec1daa85ac29be14f500b25bd3b365f01bd0cb8b0251e852e17de42cb75cd494aea0c9bd34a3144fd41f37b8e7b2ff",
          "sha256": "cd7d7753aa26d60e7f0e8886b1684752f39e02f6ac3a0af375f0b2937c8e6e78",
          "sha1": "fb6444e3e37859eab9efc9cdf6cbdc5eafe7a030",
          "md5": "e57871508bb4a688c7b3a4cc43948555"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "libSessionUtils-2.9-sources.jar",
          "url": "libSessionUtils-2.9-sources.jar",
          "size": 70829,
          "sha512": "528df843228b5f406b1507261eec88a1c1839610c6d7c93f6177b3c2528505f8a6ff5fb8698db5d4c577070ecedbae4aefa30bcc9cbf4c2c4fb9d91a54af769b",
          "sha256": "e4ff045193c9a3d8dfceed4dadc4f7b4bbd4902e4b09fd7d6de33bc23eb78b3b",
          "sha1": "87bedd22d79f090c7b2b17ed8ca542a671887dee",
          "md5": "c7be3a4932a7fe0857e616e4e2e44a73"
        }
      ]
    }
  ]
}
