{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libSessionUtils",
    "version": "2.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libSessionUtils-2.9.aar",
          "url": "libSessionUtils-2.9.aar",
          "size": 160735,
          "sha512": "44fb903f3d280ac7dc8ae82aab28b494b02a92fd35b78c2e769ece6a81ba581e22e26218f8961e47416f13219c605917432c44de88407e89ecd5fa61c21476ec",
          "sha256": "0e75eea90c49595775adb4b069f57048ec12b377502fb4152971a866b5b0d0f2",
          "sha1": "8481ead3736ef0971c14e71156e3a1d5c303dc27",
          "md5": "3e992864259a627d37f339914d48d1ee"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.zhuchao.android",
          "module": "libBaseUtils",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libFOSUtils",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libDNetUtils",
          "version": {
            "requires": "2.1"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libGXMediaUtils",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libCameraUtils",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libOpenDetection",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libGXPlayerUtils",
          "version": {
            "requires": "3.0"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libFPersistUtils",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.media",
          "module": "media",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "libSessionUtils-2.9.aar",
          "url": "libSessionUtils-2.9.aar",
          "size": 160735,
          "sha512": "44fb903f3d280ac7dc8ae82aab28b494b02a92fd35b78c2e769ece6a81ba581e22e26218f8961e47416f13219c605917432c44de88407e89ecd5fa61c21476ec",
          "sha256": "0e75eea90c49595775adb4b069f57048ec12b377502fb4152971a866b5b0d0f2",
          "sha1": "8481ead3736ef0971c14e71156e3a1d5c303dc27",
          "md5": "3e992864259a627d37f339914d48d1ee"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "libSessionUtils-2.9-sources.jar",
          "url": "libSessionUtils-2.9-sources.jar",
          "size": 70835,
          "sha512": "564addebf612fd84a73738499ca1688becdb6769169fed67ee56f78c1c9b1c534ef32de1765bbacc7654454799a33f8a711b53edb4898e3fae7f97737430151b",
          "sha256": "64dbf46adde6234b2e6353d5205fa43dd166510ca0bc981455eb55b72e96bc72",
          "sha1": "45ea21124ec0778a673c858d6aaae6ef6cbe21bf",
          "md5": "1d6c5b008e9db175b85613fdae609551"
        }
      ]
    }
  ]
}
