{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libFOSUtils",
    "version": "1.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libFOSUtils-1.4.2.aar",
          "url": "libFOSUtils-1.4.2.aar",
          "size": 207801,
          "sha512": "be1deaeb959c47b79bce8d7d678097ad719faa560bcfe11c99af7a9aaf65afff57fb12837e99b51e1463a9d307e37ebb482da750ea0efcc9a40773ad48ed4089",
          "sha256": "5fe687537e4d4c1a828b1bf0b16dab425185954a6c9a77441852531d9a55acce",
          "sha1": "e0e7029c56e08ca2d12ff0a34e66a38dc10e9e4d",
          "md5": "87dc0c5146dcb4dbdb9718edb6f96254"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.zhuchao.android",
          "module": "libBaseUtils",
          "version": {
            "requires": "2.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "libFOSUtils-1.4.2.aar",
          "url": "libFOSUtils-1.4.2.aar",
          "size": 207801,
          "sha512": "be1deaeb959c47b79bce8d7d678097ad719faa560bcfe11c99af7a9aaf65afff57fb12837e99b51e1463a9d307e37ebb482da750ea0efcc9a40773ad48ed4089",
          "sha256": "5fe687537e4d4c1a828b1bf0b16dab425185954a6c9a77441852531d9a55acce",
          "sha1": "e0e7029c56e08ca2d12ff0a34e66a38dc10e9e4d",
          "md5": "87dc0c5146dcb4dbdb9718edb6f96254"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "libFOSUtils-1.4.2-sources.jar",
          "url": "libFOSUtils-1.4.2-sources.jar",
          "size": 77198,
          "sha512": "c33ecf70539616879ad06428c0fd366a9f1844faa2edf1ac641211f619478f46c6b98bd8e424563450c4c4cf8f9870071656fa3ca90cbcf46e0f5026ebcd2820",
          "sha256": "a798c55afe24568351a7ba13f5a034d80d8020388ab206f00ee5f731ea56ae87",
          "sha1": "6dcd7395414d8424aa66d9668be6645fa41291e5",
          "md5": "84230ce5418301e68e0148d43fa89e89"
        }
      ]
    }
  ]
}
