{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libSessionUtils",
    "version": "2.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libSessionUtils-2.9.1.aar",
          "url": "libSessionUtils-2.9.1.aar",
          "size": 167750,
          "sha512": "797790e5f58b3e23f7dbcccd5db0ae23a4afea027293f2ea3179e035ea84b5ae8d070c92b8e5b8ee7b747469425791cfc2a6715cddd425300f6c898c29db9254",
          "sha256": "73d370403916dfe164229c166cc0a1d6418ab60b5b85fbdc3ca8baff9cd3001b",
          "sha1": "656e89a83644c19bf6c09039a675d57452dd0156",
          "md5": "e125c871194f7dbc989b7bb2a0aae2e2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.media",
          "module": "media",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libBaseUtils",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libFOSUtils",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libDNetUtils",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libGXMediaUtils",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libGXPlayerUtils",
          "version": {
            "requires": "3.0"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libFPersistUtils",
          "version": {
            "requires": "1.2"
          }
        }
      ],
      "files": [
        {
          "name": "libSessionUtils-2.9.1.aar",
          "url": "libSessionUtils-2.9.1.aar",
          "size": 167750,
          "sha512": "797790e5f58b3e23f7dbcccd5db0ae23a4afea027293f2ea3179e035ea84b5ae8d070c92b8e5b8ee7b747469425791cfc2a6715cddd425300f6c898c29db9254",
          "sha256": "73d370403916dfe164229c166cc0a1d6418ab60b5b85fbdc3ca8baff9cd3001b",
          "sha1": "656e89a83644c19bf6c09039a675d57452dd0156",
          "md5": "e125c871194f7dbc989b7bb2a0aae2e2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "libSessionUtils-2.9.1-sources.jar",
          "url": "libSessionUtils-2.9.1-sources.jar",
          "size": 72929,
          "sha512": "c3af0158f2c42048bdb09ccf35a0cdda40ca944e380b884a5ff68616594eafd4cdd912581fb662e8111398ea105cb25b936e31ed3d72abffe9688304f4eaef3a",
          "sha256": "f281d58d92ac3860644f747d20e1042727c42b79eee9e9bdddca5e493686cc29",
          "sha1": "a9c5b2de31d333d741c9bab836ef41aac44af7f3",
          "md5": "0aac08de94016f77bfcc8214f6839697"
        }
      ]
    }
  ]
}
