{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libSessionUtils",
    "version": "2.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libSessionUtils-2.9.1.aar",
          "url": "libSessionUtils-2.9.1.aar",
          "size": 166859,
          "sha512": "6ae05aa448b98024fc0fb435f286954954f0881b6e468891038e573f70fec41bc095e968a39f56e6363a5c260ec3b47b135e7342ca2bcac925247566c4b5f907",
          "sha256": "79cba87720e0c4c1264dc34c6196a5d345f80c7e12730cfffb3675ca239c1a1f",
          "sha1": "7f4b6c62fc56a4ae3a28033ea7089048440b915e",
          "md5": "7b3583b906377c93133902839572e944"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.media",
          "module": "media",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libBaseUtils",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libFOSUtils",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libDNetUtils",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libGXMediaUtils",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libGXPlayerUtils",
          "version": {
            "requires": "3.0"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libFPersistUtils",
          "version": {
            "requires": "1.2"
          }
        }
      ],
      "files": [
        {
          "name": "libSessionUtils-2.9.1.aar",
          "url": "libSessionUtils-2.9.1.aar",
          "size": 166859,
          "sha512": "6ae05aa448b98024fc0fb435f286954954f0881b6e468891038e573f70fec41bc095e968a39f56e6363a5c260ec3b47b135e7342ca2bcac925247566c4b5f907",
          "sha256": "79cba87720e0c4c1264dc34c6196a5d345f80c7e12730cfffb3675ca239c1a1f",
          "sha1": "7f4b6c62fc56a4ae3a28033ea7089048440b915e",
          "md5": "7b3583b906377c93133902839572e944"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "libSessionUtils-2.9.1-sources.jar",
          "url": "libSessionUtils-2.9.1-sources.jar",
          "size": 72531,
          "sha512": "83f29f526adff544c980e21fd93a8807aabac80bb9cef42db81d3ec167eab06c7675615d654d52cf8c0005b72ccfd1eb19a0a341f731eccff5e5b8bfdb6ef4c8",
          "sha256": "c42004f6913c419c227a87cb155104481526878e9e14b09a707acfb6cb6a1cd5",
          "sha1": "c259a463826577dfe164bd8b06db11be18590790",
          "md5": "ed23e1f22f42a5fe2b1490d121b55376"
        }
      ]
    }
  ]
}
