{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libSessionUtils",
    "version": "2.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libSessionUtils-2.9.1.aar",
          "url": "libSessionUtils-2.9.1.aar",
          "size": 166865,
          "sha512": "392c6a94fbdbca7b3a443e422b9c28c20215c5764564b912ad397a09761a0f32cb3634a8d2193b5dc5dbeaec5c65c82f3f182013a21b1b7205c0002e36a8f1e9",
          "sha256": "7154916c837fcdbd42b9f96ba2e58c0dc79dd0ce9c0ec7ed2b9166a47ef180be",
          "sha1": "20d6a8365d013898c9c447fb14fde7a44ca8f52a",
          "md5": "fcc27e3166372ca0c65e7ecfd7f51e56"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.media",
          "module": "media",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libBaseUtils",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libFOSUtils",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libDNetUtils",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libGXMediaUtils",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libGXPlayerUtils",
          "version": {
            "requires": "3.0"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libFPersistUtils",
          "version": {
            "requires": "1.2"
          }
        }
      ],
      "files": [
        {
          "name": "libSessionUtils-2.9.1.aar",
          "url": "libSessionUtils-2.9.1.aar",
          "size": 166865,
          "sha512": "392c6a94fbdbca7b3a443e422b9c28c20215c5764564b912ad397a09761a0f32cb3634a8d2193b5dc5dbeaec5c65c82f3f182013a21b1b7205c0002e36a8f1e9",
          "sha256": "7154916c837fcdbd42b9f96ba2e58c0dc79dd0ce9c0ec7ed2b9166a47ef180be",
          "sha1": "20d6a8365d013898c9c447fb14fde7a44ca8f52a",
          "md5": "fcc27e3166372ca0c65e7ecfd7f51e56"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "libSessionUtils-2.9.1-sources.jar",
          "url": "libSessionUtils-2.9.1-sources.jar",
          "size": 72534,
          "sha512": "57f07382af83a1ae8aa11d08c05057c5eea6317e417e30b825fef0bc8bd725b230d5999845c151275900439e255064c6aa11f20d94ef5b1bd381c0dc48429470",
          "sha256": "d6da0ad5d58fcdbf73191446a52495bd29cb5db687e6e3f6527e7816784edaae",
          "sha1": "c8cac4921cf5ea5bd2a1ac72f64f9177466852c2",
          "md5": "294339644bcbbfe1e4ff5a12bb7374ae"
        }
      ]
    }
  ]
}
