{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libPlayUtil",
    "version": "2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libPlayUtil-2.2.aar",
          "url": "libPlayUtil-2.2.aar",
          "size": 22775,
          "sha512": "1ac5882b73996ab42312a5e2179960734242fed09301cbcf628dab93b86d849cb879c7087f931c28246c0ea4422b10bc0bdd910b3a5e7e023d68c8512b974e48",
          "sha256": "83f64a386eca0f6e4244e637e1727e6dc0db01bdb59555db281577a603267c73",
          "sha1": "2ebf575c6349ddf2988e1e2010a996d138d3f9c8",
          "md5": "1413e4df1a0e5539b97b11bc68ea7d71"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.zhuchao.android",
          "module": "libDecodeCore",
          "version": {
            "requires": "2.1"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libCallbackEvent",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "libPlayUtil-2.2.aar",
          "url": "libPlayUtil-2.2.aar",
          "size": 22775,
          "sha512": "1ac5882b73996ab42312a5e2179960734242fed09301cbcf628dab93b86d849cb879c7087f931c28246c0ea4422b10bc0bdd910b3a5e7e023d68c8512b974e48",
          "sha256": "83f64a386eca0f6e4244e637e1727e6dc0db01bdb59555db281577a603267c73",
          "sha1": "2ebf575c6349ddf2988e1e2010a996d138d3f9c8",
          "md5": "1413e4df1a0e5539b97b11bc68ea7d71"
        }
      ]
    }
  ]
}
