{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libPlayUtil",
    "version": "2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libPlayUtil-2.2.aar",
          "url": "libPlayUtil-2.2.aar",
          "size": 32354,
          "sha512": "6faa2567d88e683ecaf8d15136758759e4f42cb3fa5829fddd04363363bf696eaf9a4b1c8f1a9b4d2399167eee589d400321612ad78b2de14475e36f4e9ea52a",
          "sha256": "5fb6bfa201b333958fd3bb796f61fba904fb3ca89eb5e56e4e49f04abf3bf8e0",
          "sha1": "2c4bcfa0cd67d49fb993cab2256f10f60551c6f6",
          "md5": "46b31c7c74c607a000736c0670fe053c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.zhuchao.android",
          "module": "libFileUtils",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libDecodeCore",
          "version": {
            "requires": "2.1"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libCallbackEvent",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "libPlayUtil-2.2.aar",
          "url": "libPlayUtil-2.2.aar",
          "size": 32354,
          "sha512": "6faa2567d88e683ecaf8d15136758759e4f42cb3fa5829fddd04363363bf696eaf9a4b1c8f1a9b4d2399167eee589d400321612ad78b2de14475e36f4e9ea52a",
          "sha256": "5fb6bfa201b333958fd3bb796f61fba904fb3ca89eb5e56e4e49f04abf3bf8e0",
          "sha1": "2c4bcfa0cd67d49fb993cab2256f10f60551c6f6",
          "md5": "46b31c7c74c607a000736c0670fe053c"
        }
      ]
    }
  ]
}
