{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libApplicationUtils",
    "version": "2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libApplicationUtils-2.0.aar",
          "url": "libApplicationUtils-2.0.aar",
          "size": 4576,
          "sha512": "41c8187fb8de32a2a82e1dfa2c40ec6e2b9d29368de2ab594f8db08bacb052ae52f898173b199b158602e7214fca571198e760aa03811e31ffcd6ff1bf205fec",
          "sha256": "ee5de2ce5d80f6d9b174f9f92f0269c3bb0cd17f5010bdd82ad9ec608e4e9e33",
          "sha1": "ddb3d0389e8467fd9aa1f6cd846886e07768cb2d",
          "md5": "5edb278f5a1660785f32ecc722803083"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "libApplicationUtils-2.0.aar",
          "url": "libApplicationUtils-2.0.aar",
          "size": 4576,
          "sha512": "41c8187fb8de32a2a82e1dfa2c40ec6e2b9d29368de2ab594f8db08bacb052ae52f898173b199b158602e7214fca571198e760aa03811e31ffcd6ff1bf205fec",
          "sha256": "ee5de2ce5d80f6d9b174f9f92f0269c3bb0cd17f5010bdd82ad9ec608e4e9e33",
          "sha1": "ddb3d0389e8467fd9aa1f6cd846886e07768cb2d",
          "md5": "5edb278f5a1660785f32ecc722803083"
        }
      ]
    }
  ]
}
