{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libFileUtils",
    "version": "1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libFileUtils-1.2.aar",
          "url": "libFileUtils-1.2.aar",
          "size": 48912,
          "sha512": "d1fdc6c1a349a3ace70891accd55239b56b5a58e439df22225af8c0605ad4a63fbe428265104799905288a8e84d18bff30008c054e33fece61f0a418d3290111",
          "sha256": "77bd5f981dda38df50f2c260c7f4d0c9caa65466fc6c3d86ca6087df853f88e5",
          "sha1": "f334213000ca7d150721366e2e3822b80421ae0f",
          "md5": "bfb84816f20c170c2e3aa74c1f964690"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "libFileUtils-1.2.aar",
          "url": "libFileUtils-1.2.aar",
          "size": 48912,
          "sha512": "d1fdc6c1a349a3ace70891accd55239b56b5a58e439df22225af8c0605ad4a63fbe428265104799905288a8e84d18bff30008c054e33fece61f0a418d3290111",
          "sha256": "77bd5f981dda38df50f2c260c7f4d0c9caa65466fc6c3d86ca6087df853f88e5",
          "sha1": "f334213000ca7d150721366e2e3822b80421ae0f",
          "md5": "bfb84816f20c170c2e3aa74c1f964690"
        }
      ]
    }
  ]
}
