{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libINetUtils",
    "version": "2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.0.0-alpha.8"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.0.0-alpha.10"
          }
        }
      ],
      "files": [
        {
          "name": "libINetUtils-2.0.aar",
          "url": "libINetUtils-2.0.aar",
          "size": 46349,
          "sha512": "fef35e85221096a502e59699f4946f2a99b8ffe6f6d730d8e9f28107d19950ee752c5d0698be07c1e9c689de37e28f5669b8eda9b7c9c4c288dd199c7b962cc1",
          "sha256": "1af0551b746be97a143d60a6cdb7857806a643376c070c6a4bc5ce1c030e96c7",
          "sha1": "8ced19590898ffbfd395a2c20768c7dea94620dc",
          "md5": "ce04d5dc286aa8d93ad5abfbc40f6df1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.zhuchao.android",
          "module": "libEventInterface",
          "version": {
            "requires": "1.6"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libFBaseUitls",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.0.0-alpha.8"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.0.0-alpha.10"
          }
        }
      ],
      "files": [
        {
          "name": "libINetUtils-2.0.aar",
          "url": "libINetUtils-2.0.aar",
          "size": 46349,
          "sha512": "fef35e85221096a502e59699f4946f2a99b8ffe6f6d730d8e9f28107d19950ee752c5d0698be07c1e9c689de37e28f5669b8eda9b7c9c4c288dd199c7b962cc1",
          "sha256": "1af0551b746be97a143d60a6cdb7857806a643376c070c6a4bc5ce1c030e96c7",
          "sha1": "8ced19590898ffbfd395a2c20768c7dea94620dc",
          "md5": "ce04d5dc286aa8d93ad5abfbc40f6df1"
        }
      ]
    }
  ]
}
