{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libINetUtils",
    "version": "2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.0.0-alpha.8"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.0.0-alpha.11"
          }
        }
      ],
      "files": [
        {
          "name": "libINetUtils-2.0.aar",
          "url": "libINetUtils-2.0.aar",
          "size": 48824,
          "sha512": "1905d681983e009b6454d9ded4a0af576bdaaab6bc024920d1a2c1687b7361b27595239194a369925839674b459acca9a47879dd9e7b99c1c0de06c3b2e38097",
          "sha256": "dd05f5e361e2826c35f1c69ebe261181835586f97b6d6141cc9533eabcde8f51",
          "sha1": "74ef02f704e9b180526ccbe2aee8313a68c8689b",
          "md5": "dd59fdb939d326a68a46191de0ecd1bf"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.zhuchao.android",
          "module": "libEventInterface",
          "version": {
            "requires": "1.6"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libFBaseUtils",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-crashlytics-buildtools",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.0.0-alpha.8"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.0.0-alpha.11"
          }
        }
      ],
      "files": [
        {
          "name": "libINetUtils-2.0.aar",
          "url": "libINetUtils-2.0.aar",
          "size": 48824,
          "sha512": "1905d681983e009b6454d9ded4a0af576bdaaab6bc024920d1a2c1687b7361b27595239194a369925839674b459acca9a47879dd9e7b99c1c0de06c3b2e38097",
          "sha256": "dd05f5e361e2826c35f1c69ebe261181835586f97b6d6141cc9533eabcde8f51",
          "sha1": "74ef02f704e9b180526ccbe2aee8313a68c8689b",
          "md5": "dd59fdb939d326a68a46191de0ecd1bf"
        }
      ]
    }
  ]
}
