{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libINetUtils",
    "version": "2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.0.0-alpha.8"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.0.0-alpha.8"
          }
        }
      ],
      "files": [
        {
          "name": "libINetUtils-2.0.aar",
          "url": "libINetUtils-2.0.aar",
          "size": 43923,
          "sha512": "f045a7c1ec04a384fd5ad663e807c90dd8c3a2d88976a6482b2dfbe8e88935470374da9651beb139dcd3e03f3972830f172eec42a46cdc3cc1a6f7aaf937f017",
          "sha256": "e002d14df7f73903a76ebac701735fa9079215bee7eba8e03d7c6f6ebcb190bb",
          "sha1": "f99c9ffd77afd1a2aada7de87759ca9bfeb3af33",
          "md5": "e2b66fc6fde1236dedd524800c455130"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.zhuchao.android",
          "module": "libCallbackEvent",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libFileUtils",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.0.0-alpha.8"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.0.0-alpha.8"
          }
        }
      ],
      "files": [
        {
          "name": "libINetUtils-2.0.aar",
          "url": "libINetUtils-2.0.aar",
          "size": 43923,
          "sha512": "f045a7c1ec04a384fd5ad663e807c90dd8c3a2d88976a6482b2dfbe8e88935470374da9651beb139dcd3e03f3972830f172eec42a46cdc3cc1a6f7aaf937f017",
          "sha256": "e002d14df7f73903a76ebac701735fa9079215bee7eba8e03d7c6f6ebcb190bb",
          "sha1": "f99c9ffd77afd1a2aada7de87759ca9bfeb3af33",
          "md5": "e2b66fc6fde1236dedd524800c455130"
        }
      ]
    }
  ]
}
