{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libPlayerUtils",
    "version": "2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libPlayerUtils-2.3.aar",
          "url": "libPlayerUtils-2.3.aar",
          "size": 31963,
          "sha512": "e65c3424c04c50c359fe3c4def03a118cfe892750d8246463d642081f848aaacec44bad7ddd65ebc37bce8e531cd2f3f5069770f1dff88ad7e9af1cfdb6c0e1e",
          "sha256": "678d0fa62055ad681e5f783e43e281b388f21d2782a123a868ba89e32465ef78",
          "sha1": "8e3d4f7095512d14f073797685c51573428b3f6c",
          "md5": "fc77c05dbcc7923abe399e84cd316835"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.zhuchao.android",
          "module": "libOSUtils",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libFileUtils",
          "version": {
            "requires": "1.5"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libDecodeCore",
          "version": {
            "requires": "2.1"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libCallbackEvent",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "libPlayerUtils-2.3.aar",
          "url": "libPlayerUtils-2.3.aar",
          "size": 31963,
          "sha512": "e65c3424c04c50c359fe3c4def03a118cfe892750d8246463d642081f848aaacec44bad7ddd65ebc37bce8e531cd2f3f5069770f1dff88ad7e9af1cfdb6c0e1e",
          "sha256": "678d0fa62055ad681e5f783e43e281b388f21d2782a123a868ba89e32465ef78",
          "sha1": "8e3d4f7095512d14f073797685c51573428b3f6c",
          "md5": "fc77c05dbcc7923abe399e84cd316835"
        }
      ]
    }
  ]
}
