{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libVideo",
    "version": "1.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libVideo-1.5.aar",
          "url": "libVideo-1.5.aar",
          "size": 27670,
          "sha512": "a7c08f84e35234ca07e92ad73c8a52bea1ec5fd973867e4a530d5cc7e5dea1ac34d48867f32a5d34631a57626e8d5b3440e19c157a6ca8dcf1f9e24206d3911a",
          "sha256": "f22fc7ee5fb8582952caf6825a163ccfce6c9ae9b989d41288bb97a5abbbda2c",
          "sha1": "15ec8377dff9a1656a003a4311e557ac3a8fa94c",
          "md5": "913eb0821a2bce3260d4822bd5be44a4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libCallbackEvent",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libPlayUtil",
          "version": {
            "requires": "2.3"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libNetUtil",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libDataBaseUtil",
          "version": {
            "requires": "2.1"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libFileUtils",
          "version": {
            "requires": "1.4"
          }
        }
      ],
      "files": [
        {
          "name": "libVideo-1.5.aar",
          "url": "libVideo-1.5.aar",
          "size": 27670,
          "sha512": "a7c08f84e35234ca07e92ad73c8a52bea1ec5fd973867e4a530d5cc7e5dea1ac34d48867f32a5d34631a57626e8d5b3440e19c157a6ca8dcf1f9e24206d3911a",
          "sha256": "f22fc7ee5fb8582952caf6825a163ccfce6c9ae9b989d41288bb97a5abbbda2c",
          "sha1": "15ec8377dff9a1656a003a4311e557ac3a8fa94c",
          "md5": "913eb0821a2bce3260d4822bd5be44a4"
        }
      ]
    }
  ]
}
