{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libPlayerUtils",
    "version": "2.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libPlayerUtils-2.5.aar",
          "url": "libPlayerUtils-2.5.aar",
          "size": 212758,
          "sha512": "62661def4f1ab8559d548c7ec0d9d0c2d1933b2596a0054490b91097ef76338e12ca3992eb702725e04cb403685d5f2c4ae240dbad50d35f7bf873a5a1f79e02",
          "sha256": "2c08596ddfc7e4b5d1954a9a3d45d24e5c86b37ddbb6da14a85b4da35cce1a28",
          "sha1": "885b740309014b0585ca5d3bef937817b7c684d7",
          "md5": "cc7c6988dd55fb62d069ec21d319280f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.zhuchao.android",
          "module": "libDecodeCore",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libINetUtils",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libCallbackEvent",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libFileUtils",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libJOSUtils",
          "version": {
            "requires": "1.2"
          }
        }
      ],
      "files": [
        {
          "name": "libPlayerUtils-2.5.aar",
          "url": "libPlayerUtils-2.5.aar",
          "size": 212758,
          "sha512": "62661def4f1ab8559d548c7ec0d9d0c2d1933b2596a0054490b91097ef76338e12ca3992eb702725e04cb403685d5f2c4ae240dbad50d35f7bf873a5a1f79e02",
          "sha256": "2c08596ddfc7e4b5d1954a9a3d45d24e5c86b37ddbb6da14a85b4da35cce1a28",
          "sha1": "885b740309014b0585ca5d3bef937817b7c684d7",
          "md5": "cc7c6988dd55fb62d069ec21d319280f"
        }
      ]
    }
  ]
}
