{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libPlayerUtils",
    "version": "2.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libPlayerUtils-2.5.aar",
          "url": "libPlayerUtils-2.5.aar",
          "size": 214842,
          "sha512": "4e5dac9326ca2c59d2e4af3818c7ff47a8eebb2139bf7fa1a4901178eae782c789966d5e80d9cce4e89654e9c3d3655710cb59c54c7d46fe7375708ed58ac66c",
          "sha256": "daac4ae694d0831baa74730ffbd8c8ee6dcfcb1ebe7ba4f7fa9609a8a493709c",
          "sha1": "3a6aede264a793cdd7efac589929026c42bf9bc4",
          "md5": "d4ff7d21d1ec85b2bac0527fc5e63180"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.zhuchao.android",
          "module": "libEventInterface",
          "version": {
            "requires": "1.6"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libFBaseUtils",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libINetUtils",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libJOSUtils",
          "version": {
            "requires": "1.2"
          }
        }
      ],
      "files": [
        {
          "name": "libPlayerUtils-2.5.aar",
          "url": "libPlayerUtils-2.5.aar",
          "size": 214842,
          "sha512": "4e5dac9326ca2c59d2e4af3818c7ff47a8eebb2139bf7fa1a4901178eae782c789966d5e80d9cce4e89654e9c3d3655710cb59c54c7d46fe7375708ed58ac66c",
          "sha256": "daac4ae694d0831baa74730ffbd8c8ee6dcfcb1ebe7ba4f7fa9609a8a493709c",
          "sha1": "3a6aede264a793cdd7efac589929026c42bf9bc4",
          "md5": "d4ff7d21d1ec85b2bac0527fc5e63180"
        }
      ]
    }
  ]
}
