{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libVideo",
    "version": "1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libVideo-1.4.aar",
          "url": "libVideo-1.4.aar",
          "size": 27138,
          "sha512": "274aaadfaccf23f66af247358dd3967da0e397ad671d2b0f44575b49880460e1c285650d833ca3534681aaaeab880306d701e8c3e1199f841a9ef1a3fb0aa5b6",
          "sha256": "9b801cc655aeeab2de1a902f5f4c200989914b25e3f526f98a111f62b9d3e874",
          "sha1": "dc78cc3054efe6ec02a5a7979d530df5a4499afc",
          "md5": "eee962e5beaaecd074eaa27638458ab1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libCallbackEvent",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libPlayUtil",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libNetUtil",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libDataBaseUtil",
          "version": {
            "requires": "2.1"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libFileUtils",
          "version": {
            "requires": "1.3"
          }
        }
      ],
      "files": [
        {
          "name": "libVideo-1.4.aar",
          "url": "libVideo-1.4.aar",
          "size": 27138,
          "sha512": "274aaadfaccf23f66af247358dd3967da0e397ad671d2b0f44575b49880460e1c285650d833ca3534681aaaeab880306d701e8c3e1199f841a9ef1a3fb0aa5b6",
          "sha256": "9b801cc655aeeab2de1a902f5f4c200989914b25e3f526f98a111f62b9d3e874",
          "sha1": "dc78cc3054efe6ec02a5a7979d530df5a4499afc",
          "md5": "eee962e5beaaecd074eaa27638458ab1"
        }
      ]
    }
  ]
}
