{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libVideo",
    "version": "1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libVideo-1.4.aar",
          "url": "libVideo-1.4.aar",
          "size": 33418,
          "sha512": "7f5e27457fc6b7f63164cd245314f8a60acf9660ba5841d6f8e5e208b2cb00457ba1dc0efc220f74b6e2525a83beebc920a14c5c7f2c795494e97ec72d3b1359",
          "sha256": "1c68b7ba64655e6bc0478fd733cdf3986112afeb29227bde4b66fa626727175c",
          "sha1": "e3cb922007242c08c1c80e903b0fdec396043294",
          "md5": "bf18be112f0b9afcd7045ebe63b8da15"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libCallbackEvent",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libPlayUtil",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libNetUtil",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libDataBaseUtil",
          "version": {
            "requires": "2.1"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libFileUtils",
          "version": {
            "requires": "1.3"
          }
        }
      ],
      "files": [
        {
          "name": "libVideo-1.4.aar",
          "url": "libVideo-1.4.aar",
          "size": 33418,
          "sha512": "7f5e27457fc6b7f63164cd245314f8a60acf9660ba5841d6f8e5e208b2cb00457ba1dc0efc220f74b6e2525a83beebc920a14c5c7f2c795494e97ec72d3b1359",
          "sha256": "1c68b7ba64655e6bc0478fd733cdf3986112afeb29227bde4b66fa626727175c",
          "sha1": "e3cb922007242c08c1c80e903b0fdec396043294",
          "md5": "bf18be112f0b9afcd7045ebe63b8da15"
        }
      ]
    }
  ]
}
