{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libFBaseUtils",
    "version": "2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "com.google.android.things",
          "module": "androidthings",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.0.0-alpha.11"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.0.0-alpha.11"
          }
        }
      ],
      "files": [
        {
          "name": "libFBaseUtils-2.1.aar",
          "url": "libFBaseUtils-2.1.aar",
          "size": 102199,
          "sha512": "69f50f9d70265a6bc6132e7cc5d6017c28237090dd76bd27099a70b1ea44ed8c399018762b5687cba4964c8181d3ed7c502719939675d7a04d6f81cac61d544e",
          "sha256": "f9cc9a75087e6c496f244a37d1561b4518666a85825a9b133c15076428c73a32",
          "sha1": "18ee589986d5560d7bf37db04ee8dceb514c8927",
          "md5": "24eb3c4d490f24589c8b0694f7ebae27"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "com.google.android.things",
          "module": "androidthings",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.0.0-alpha.11"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.0.0-alpha.11"
          }
        }
      ],
      "files": [
        {
          "name": "libFBaseUtils-2.1.aar",
          "url": "libFBaseUtils-2.1.aar",
          "size": 102199,
          "sha512": "69f50f9d70265a6bc6132e7cc5d6017c28237090dd76bd27099a70b1ea44ed8c399018762b5687cba4964c8181d3ed7c502719939675d7a04d6f81cac61d544e",
          "sha256": "f9cc9a75087e6c496f244a37d1561b4518666a85825a9b133c15076428c73a32",
          "sha1": "18ee589986d5560d7bf37db04ee8dceb514c8927",
          "md5": "24eb3c4d490f24589c8b0694f7ebae27"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "libFBaseUtils-2.1-sources.jar",
          "url": "libFBaseUtils-2.1-sources.jar",
          "size": 54844,
          "sha512": "997405c012da596efa725f65951c21123cf7e430b6d6815c7988bad1ac705c9f155322b9f2f6e789bd90a4b32cfca4d13d37b60c89abd948e74a73569e34da30",
          "sha256": "435fa0ad268b13a2efe6be48e48177029d356cbb2aad34f11d6f0113fec437b2",
          "sha1": "2ad2a13e09f4868ab3d39a3febf4c5571af4cc4a",
          "md5": "6e85ec658fab4a96932e496c119d5f5c"
        }
      ]
    }
  ]
}
