{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libFileUtils",
    "version": "1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libFileUtils-1.4.aar",
          "url": "libFileUtils-1.4.aar",
          "size": 65621,
          "sha512": "d19187ecf430307c3f15deeb5b23285287108a4a4b5c5a35d66f85eb2a33c3991c42bfb7ef32725157baafae1721082d1a62df26cba47fe9fcbb1c31c1755e37",
          "sha256": "3e161f575e9a5effbe627cff7dbfa974839dfef29b78a1838870bfe35b21b176",
          "sha1": "1484aa87b63f79d69e7f7e039e58b690ab8cbdb9",
          "md5": "76b3255da1b65eaeafd07ccaf3e4c212"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libCallbackEvent",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libOSUtils",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "libFileUtils-1.4.aar",
          "url": "libFileUtils-1.4.aar",
          "size": 65621,
          "sha512": "d19187ecf430307c3f15deeb5b23285287108a4a4b5c5a35d66f85eb2a33c3991c42bfb7ef32725157baafae1721082d1a62df26cba47fe9fcbb1c31c1755e37",
          "sha256": "3e161f575e9a5effbe627cff7dbfa974839dfef29b78a1838870bfe35b21b176",
          "sha1": "1484aa87b63f79d69e7f7e039e58b690ab8cbdb9",
          "md5": "76b3255da1b65eaeafd07ccaf3e4c212"
        }
      ]
    }
  ]
}
