{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libFileUtils",
    "version": "1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libFileUtils-1.4.aar",
          "url": "libFileUtils-1.4.aar",
          "size": 54996,
          "sha512": "42ba696dcbcdf7e57aa766aaf03af85b255664203f7848e74801c0672e04d7a982d7fea57f1720cd3a62dc709072769bd5577c0581648aff06f691c715f20ca7",
          "sha256": "dcea672732001a7b7fb8a3d6b7989c11b113796990aefaa0153e211ae20cf27a",
          "sha1": "4ffd8277c17a188f4a6e887f0c14d9d68650c5c5",
          "md5": "7e41d19dafda5286b6103239bd16d318"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libCallbackEvent",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "libFileUtils-1.4.aar",
          "url": "libFileUtils-1.4.aar",
          "size": 54996,
          "sha512": "42ba696dcbcdf7e57aa766aaf03af85b255664203f7848e74801c0672e04d7a982d7fea57f1720cd3a62dc709072769bd5577c0581648aff06f691c715f20ca7",
          "sha256": "dcea672732001a7b7fb8a3d6b7989c11b113796990aefaa0153e211ae20cf27a",
          "sha1": "4ffd8277c17a188f4a6e887f0c14d9d68650c5c5",
          "md5": "7e41d19dafda5286b6103239bd16d318"
        }
      ]
    }
  ]
}
