{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libFBaseUitls",
    "version": "1.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0-alpha02"
          }
        }
      ],
      "files": [
        {
          "name": "libFBaseUitls-1.8.aar",
          "url": "libFBaseUitls-1.8.aar",
          "size": 88830,
          "sha512": "d575e0f7e2e18cc6c390f527ea5ada2ecd51dad0245c8d2188757cf45a4af3d35c1041a75a40e134d6722e506ddb024853a84fe40e6dca4ca45ae095cdb55ab9",
          "sha256": "f99470c5b21aaf319d65a60e7a16f377dd39550bc5c50da5504cfe5b5c310511",
          "sha1": "e521412372d77a20518933e2358e160ed556d369",
          "md5": "03b6374f13e9bb7e859d3c252bffee6c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.zhuchao.android",
          "module": "libEventInterface",
          "version": {
            "requires": "1.6"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.0-alpha01"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0-alpha02"
          }
        }
      ],
      "files": [
        {
          "name": "libFBaseUitls-1.8.aar",
          "url": "libFBaseUitls-1.8.aar",
          "size": 88830,
          "sha512": "d575e0f7e2e18cc6c390f527ea5ada2ecd51dad0245c8d2188757cf45a4af3d35c1041a75a40e134d6722e506ddb024853a84fe40e6dca4ca45ae095cdb55ab9",
          "sha256": "f99470c5b21aaf319d65a60e7a16f377dd39550bc5c50da5504cfe5b5c310511",
          "sha1": "e521412372d77a20518933e2358e160ed556d369",
          "md5": "03b6374f13e9bb7e859d3c252bffee6c"
        }
      ]
    }
  ]
}
