{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libFBaseUitls",
    "version": "1.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0-alpha02"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10"
          }
        }
      ],
      "files": [
        {
          "name": "libFBaseUitls-1.8.aar",
          "url": "libFBaseUitls-1.8.aar",
          "size": 99361,
          "sha512": "f11153342b28b8af702fe7535da44708f78553c5d073bf90e5149ce743ecf2d7002bf965b2853e6ad8188f4edac1a87b14aadf18b20c0ea8d388c14b9f8c9c36",
          "sha256": "8027ef40402b59c041228d98c26746a541a1ffae6b157b0db790940758f0dec2",
          "sha1": "a0a92efa231ae21aaa3d466df33b0da1c7fb8900",
          "md5": "f091d26a8955a06227200ddf8154cecc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.zhuchao.android",
          "module": "libEventInterface",
          "version": {
            "requires": "1.6"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.0-alpha01"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0-alpha02"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10"
          }
        }
      ],
      "files": [
        {
          "name": "libFBaseUitls-1.8.aar",
          "url": "libFBaseUitls-1.8.aar",
          "size": 99361,
          "sha512": "f11153342b28b8af702fe7535da44708f78553c5d073bf90e5149ce743ecf2d7002bf965b2853e6ad8188f4edac1a87b14aadf18b20c0ea8d388c14b9f8c9c36",
          "sha256": "8027ef40402b59c041228d98c26746a541a1ffae6b157b0db790940758f0dec2",
          "sha1": "a0a92efa231ae21aaa3d466df33b0da1c7fb8900",
          "md5": "f091d26a8955a06227200ddf8154cecc"
        }
      ]
    }
  ]
}
