{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libBaseUtils",
    "version": "2.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "androidx.documentfile",
          "module": "documentfile",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.google.android.things",
          "module": "androidthings",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.0.0-alpha.14"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.0.0-alpha.14"
          }
        }
      ],
      "files": [
        {
          "name": "libBaseUtils-2.2.1.aar",
          "url": "libBaseUtils-2.2.1.aar",
          "size": 121864,
          "sha512": "56fb81bc2079b2147b56099f9b59811d7927a1d3ca37ad910f517c76594e77dae6a1ea050e00191ec400b66c8bb11455b0a715ef846fbb2a5cd2e126116cfcb9",
          "sha256": "8f8bbb148a26c2dc150b7ce16f8e37889e7d5a96abafe90ce3f06060cba3fafa",
          "sha1": "9322ebee51e95e582201cb76052c185e55caeb71",
          "md5": "88232d72938ec811f361048b570d3a14"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "2.0.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "androidx.documentfile",
          "module": "documentfile",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.google.android.things",
          "module": "androidthings",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.0.0-alpha.14"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.0.0-alpha.14"
          }
        }
      ],
      "files": [
        {
          "name": "libBaseUtils-2.2.1.aar",
          "url": "libBaseUtils-2.2.1.aar",
          "size": 121864,
          "sha512": "56fb81bc2079b2147b56099f9b59811d7927a1d3ca37ad910f517c76594e77dae6a1ea050e00191ec400b66c8bb11455b0a715ef846fbb2a5cd2e126116cfcb9",
          "sha256": "8f8bbb148a26c2dc150b7ce16f8e37889e7d5a96abafe90ce3f06060cba3fafa",
          "sha1": "9322ebee51e95e582201cb76052c185e55caeb71",
          "md5": "88232d72938ec811f361048b570d3a14"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "libBaseUtils-2.2.1-sources.jar",
          "url": "libBaseUtils-2.2.1-sources.jar",
          "size": 68562,
          "sha512": "b7199008f9fa878788c9bbe80395c67919b1808e751624959587eaf85badda55498081c3d9bf92fa7613bb51aff6a3a128d72d862841ee99ed7056cfcf781ba6",
          "sha256": "0c35482187f3723ca731bb8c8c0eaca1c6693c18392c31d484c2f77e3eb34b96",
          "sha1": "c8f8dca678515cf71af6bb1d3cb4b489255478d1",
          "md5": "255cb2ba43bc345138125fadef59b6a4"
        }
      ]
    }
  ]
}
