{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libBaseUtils",
    "version": "2.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "androidx.documentfile",
          "module": "documentfile",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.google.android.things",
          "module": "androidthings",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.0.0-alpha.14"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.0.0-alpha.14"
          }
        }
      ],
      "files": [
        {
          "name": "libBaseUtils-2.2.1.aar",
          "url": "libBaseUtils-2.2.1.aar",
          "size": 122809,
          "sha512": "daa9b6aaa32759a75fb64908ee9751ee98f68f544c023cd2a012a606ea6f1c90d99d9066556f68dc7b535c7b13edde3bbd619c2e6f2795e4969624739d5bebbe",
          "sha256": "88c876a3de3bb340e78d672f7f4545699f0daad463799aaa281162e03fdc8b72",
          "sha1": "95ac185b575d8202cce3d23267628d2db22442f0",
          "md5": "59177beabb4ff3578956e93b4b3551e2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "2.0.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "androidx.documentfile",
          "module": "documentfile",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.google.android.things",
          "module": "androidthings",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.0.0-alpha.14"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.0.0-alpha.14"
          }
        }
      ],
      "files": [
        {
          "name": "libBaseUtils-2.2.1.aar",
          "url": "libBaseUtils-2.2.1.aar",
          "size": 122809,
          "sha512": "daa9b6aaa32759a75fb64908ee9751ee98f68f544c023cd2a012a606ea6f1c90d99d9066556f68dc7b535c7b13edde3bbd619c2e6f2795e4969624739d5bebbe",
          "sha256": "88c876a3de3bb340e78d672f7f4545699f0daad463799aaa281162e03fdc8b72",
          "sha1": "95ac185b575d8202cce3d23267628d2db22442f0",
          "md5": "59177beabb4ff3578956e93b4b3551e2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "libBaseUtils-2.2.1-sources.jar",
          "url": "libBaseUtils-2.2.1-sources.jar",
          "size": 69236,
          "sha512": "0ed483e9766dbd07deda0d0669eba09908f4760b723b4edb0a5e9405448e704a374ffc80c80f80060fa5a4a6c7d1a12fd134d88f7a8f8b651f5cddad80a85182",
          "sha256": "c562f18b463854c1d9f48f64de42655f5a7f8a4c226a1c853ba7c73d2761eea6",
          "sha1": "62f293875e3558122d6d26fb874af8f5d8b26dbb",
          "md5": "04ddd5c53003702b709cc77f025c9a82"
        }
      ]
    }
  ]
}
