{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libBaseUtils",
    "version": "2.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "androidx.documentfile",
          "module": "documentfile",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.google.android.things",
          "module": "androidthings",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.0.0-alpha.14"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.0.0-alpha.14"
          }
        }
      ],
      "files": [
        {
          "name": "libBaseUtils-2.2.1.aar",
          "url": "libBaseUtils-2.2.1.aar",
          "size": 121871,
          "sha512": "fb4be3534ec6e30c2332ca7fca08c324ed27572910e25167a27bae97e523674799148b2c0019779a20539c8195801170f3d169604385ce0ac0b51f3814a76683",
          "sha256": "dac28884c8dcea6286ae07f1b5e3a0093acd1b8dcf974238d417ef7c5309194d",
          "sha1": "89d4cc0115fc065fcb45949fc6b770e4b9563ca2",
          "md5": "711837f3e17750592fb8b8fed43d8530"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "2.0.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "androidx.documentfile",
          "module": "documentfile",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.google.android.things",
          "module": "androidthings",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.0.0-alpha.14"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.0.0-alpha.14"
          }
        }
      ],
      "files": [
        {
          "name": "libBaseUtils-2.2.1.aar",
          "url": "libBaseUtils-2.2.1.aar",
          "size": 121871,
          "sha512": "fb4be3534ec6e30c2332ca7fca08c324ed27572910e25167a27bae97e523674799148b2c0019779a20539c8195801170f3d169604385ce0ac0b51f3814a76683",
          "sha256": "dac28884c8dcea6286ae07f1b5e3a0093acd1b8dcf974238d417ef7c5309194d",
          "sha1": "89d4cc0115fc065fcb45949fc6b770e4b9563ca2",
          "md5": "711837f3e17750592fb8b8fed43d8530"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "libBaseUtils-2.2.1-sources.jar",
          "url": "libBaseUtils-2.2.1-sources.jar",
          "size": 68561,
          "sha512": "c5dddfb737c623afa19b89a101f650b9b92f998be9efd3381da67cd1df303e9b57d7e8e4582d075ae88700f1de3a6d6d2387b9ee425df4f90e4c4576db17b73b",
          "sha256": "ad1bcabc8a5db11fb536e381d004f96eefa9a6884dead65ec37cb8d253ec24ec",
          "sha1": "a58b759de53ff88896ea6b9d148439d24f115007",
          "md5": "ca6f37d008cf2233f6276c2d9b8a3797"
        }
      ]
    }
  ]
}
