{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libSessionUtils",
    "version": "2.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libSessionUtils-2.4.aar",
          "url": "libSessionUtils-2.4.aar",
          "size": 70716,
          "sha512": "b55d541964a0fb5072d365918102e538c1cc67d8aa39f3643a2902bf99b008a7a72b6be36350ed0d2f0468ce8d9a0e948d74096c2e398cd8a4cd50b1928f666b",
          "sha256": "9ecb73e4258f49609e940a7eb1d40b6be5926d7bbab4932d46be3a01727752bf",
          "sha1": "73a7f4fa33d6f34fbc0492bc4e694ce9955edf25",
          "md5": "88bea2c5b0a7adabe96237697a47417e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.8"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libOSUtils",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libCallbackEvent",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libFileUtils",
          "version": {
            "requires": "1.5"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libNetUtils",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libMediaUtils",
          "version": {
            "requires": "1.5"
          }
        }
      ],
      "files": [
        {
          "name": "libSessionUtils-2.4.aar",
          "url": "libSessionUtils-2.4.aar",
          "size": 70716,
          "sha512": "b55d541964a0fb5072d365918102e538c1cc67d8aa39f3643a2902bf99b008a7a72b6be36350ed0d2f0468ce8d9a0e948d74096c2e398cd8a4cd50b1928f666b",
          "sha256": "9ecb73e4258f49609e940a7eb1d40b6be5926d7bbab4932d46be3a01727752bf",
          "sha1": "73a7f4fa33d6f34fbc0492bc4e694ce9955edf25",
          "md5": "88bea2c5b0a7adabe96237697a47417e"
        }
      ]
    }
  ]
}
