{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libDataBaseUtil",
    "version": "2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libDataBaseUtil-2.1.aar",
          "url": "libDataBaseUtil-2.1.aar",
          "size": 19444,
          "sha512": "5bc0149f11b474fd6308902bee764283bc51265d128b76c52923b2836962023457c44b9d967a79aa0f293065c855c77b0d2c8ff2c6170bfbd8952dfd1afdec8c",
          "sha256": "cfba8219e2d76048f22833af4e1cd5358566eacab5d3ad09e2b7212567e0a012",
          "sha1": "ae8a9cf2a14bae9d732a239d2dbdb302272e3243",
          "md5": "f10e8511ff9f0c74f10fe029c5298963"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.zhuchao.android",
          "module": "libFileUtils",
          "version": {
            "requires": "1.4"
          }
        }
      ],
      "files": [
        {
          "name": "libDataBaseUtil-2.1.aar",
          "url": "libDataBaseUtil-2.1.aar",
          "size": 19444,
          "sha512": "5bc0149f11b474fd6308902bee764283bc51265d128b76c52923b2836962023457c44b9d967a79aa0f293065c855c77b0d2c8ff2c6170bfbd8952dfd1afdec8c",
          "sha256": "cfba8219e2d76048f22833af4e1cd5358566eacab5d3ad09e2b7212567e0a012",
          "sha1": "ae8a9cf2a14bae9d732a239d2dbdb302272e3243",
          "md5": "f10e8511ff9f0c74f10fe029c5298963"
        }
      ]
    }
  ]
}
