{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libOVL",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libOVL-1.0.aar",
          "url": "libOVL-1.0.aar",
          "size": 55817110,
          "sha512": "7e7daadc68b1f1e06fb65c6733a7336e48df11835efa89a15a06be070899fea7b93af69a042c73598976fe520e6d2e900bb5833445e04bdc444391339d003060",
          "sha256": "bc064ef2ed13e5ed22ffb1e408b60d5c8de15dd72d418e114e70869732f7f578",
          "sha1": "4b8c8fb283683e820567f46ba4f4f6ac33387952",
          "md5": "bed1b50a41a45d87648bca786ccdb394"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.0-RC2"
          }
        }
      ],
      "files": [
        {
          "name": "libOVL-1.0.aar",
          "url": "libOVL-1.0.aar",
          "size": 55817110,
          "sha512": "7e7daadc68b1f1e06fb65c6733a7336e48df11835efa89a15a06be070899fea7b93af69a042c73598976fe520e6d2e900bb5833445e04bdc444391339d003060",
          "sha256": "bc064ef2ed13e5ed22ffb1e408b60d5c8de15dd72d418e114e70869732f7f578",
          "sha1": "4b8c8fb283683e820567f46ba4f4f6ac33387952",
          "md5": "bed1b50a41a45d87648bca786ccdb394"
        }
      ]
    }
  ]
}
