{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libMediaUtils",
    "version": "1.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libMediaUtils-1.5.aar",
          "url": "libMediaUtils-1.5.aar",
          "size": 27874,
          "sha512": "9cf569e4af9af9d249afd3810849e37c298d2f21a56c4a5ccedca32404e1f2abaa7b663fa9dc41d1366c9628ec071222f44678780dea4f567c460554ea1903ca",
          "sha256": "1a7f56809440f4122d45d69acb1a80595c8a0835712404bdf2dfedc38c166961",
          "sha1": "d47791f57d3c54b8d4ac43d2f4c2080c447e4de9",
          "md5": "8ad56b62dd39adcb4646cd08b4a99cad"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.zhuchao.android",
          "module": "libOSUtils",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libCallbackEvent",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libPlayerUtils",
          "version": {
            "requires": "2.3"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libNetUtils",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libDataBaseUtils",
          "version": {
            "requires": "2.1"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libFileUtils",
          "version": {
            "requires": "1.5"
          }
        }
      ],
      "files": [
        {
          "name": "libMediaUtils-1.5.aar",
          "url": "libMediaUtils-1.5.aar",
          "size": 27874,
          "sha512": "9cf569e4af9af9d249afd3810849e37c298d2f21a56c4a5ccedca32404e1f2abaa7b663fa9dc41d1366c9628ec071222f44678780dea4f567c460554ea1903ca",
          "sha256": "1a7f56809440f4122d45d69acb1a80595c8a0835712404bdf2dfedc38c166961",
          "sha1": "d47791f57d3c54b8d4ac43d2f4c2080c447e4de9",
          "md5": "8ad56b62dd39adcb4646cd08b4a99cad"
        }
      ]
    }
  ]
}
