{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libJOSUtils",
    "version": "1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libJOSUtils-1.3.aar",
          "url": "libJOSUtils-1.3.aar",
          "size": 50962,
          "sha512": "a1a4124315141768eb7b55de5cc90bcb28ba815ae359943ec701e8bc803e3446796c1929d079a2fcd0a26e55ab82f730cea423718b4591b90949956a53afffc2",
          "sha256": "de9283e4f83fc1b4f79d3a51c27a417c06e7b6cb17b214156055f81234119191",
          "sha1": "4f347252696c57d8668f90a3c36b2b02cccac42c",
          "md5": "af427f968132c41e2f07ea369ccaaab0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.zhuchao.android",
          "module": "libEventInterface",
          "version": {
            "requires": "1.6"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libFBaseUtils",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "com.google.android.things",
          "module": "androidthings",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "libJOSUtils-1.3.aar",
          "url": "libJOSUtils-1.3.aar",
          "size": 50962,
          "sha512": "a1a4124315141768eb7b55de5cc90bcb28ba815ae359943ec701e8bc803e3446796c1929d079a2fcd0a26e55ab82f730cea423718b4591b90949956a53afffc2",
          "sha256": "de9283e4f83fc1b4f79d3a51c27a417c06e7b6cb17b214156055f81234119191",
          "sha1": "4f347252696c57d8668f90a3c36b2b02cccac42c",
          "md5": "af427f968132c41e2f07ea369ccaaab0"
        }
      ]
    }
  ]
}
