{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libJOSUtils",
    "version": "1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libJOSUtils-1.3.aar",
          "url": "libJOSUtils-1.3.aar",
          "size": 43718,
          "sha512": "a6606d1f0ce84d8c3e296501deb6ebf4129481de435765ba6a3a426b762098e976b057677c64d88fa0bf864fee876fdb4e24f211c9a79adaec30213f034b6500",
          "sha256": "9ea6c69b588e2952994c09de526ced9081aadf681259c13abca788b025c239b2",
          "sha1": "6223c98e8e805dc65ebc3f87a963b5d200478908",
          "md5": "b2853c5a5e79141e028fa030f2ba6c34"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.zhuchao.android",
          "module": "libFBaseUtils",
          "version": {
            "requires": "2.0"
          }
        }
      ],
      "files": [
        {
          "name": "libJOSUtils-1.3.aar",
          "url": "libJOSUtils-1.3.aar",
          "size": 43718,
          "sha512": "a6606d1f0ce84d8c3e296501deb6ebf4129481de435765ba6a3a426b762098e976b057677c64d88fa0bf864fee876fdb4e24f211c9a79adaec30213f034b6500",
          "sha256": "9ea6c69b588e2952994c09de526ced9081aadf681259c13abca788b025c239b2",
          "sha1": "6223c98e8e805dc65ebc3f87a963b5d200478908",
          "md5": "b2853c5a5e79141e028fa030f2ba6c34"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "libJOSUtils-1.3-sources.jar",
          "url": "libJOSUtils-1.3-sources.jar",
          "size": 13690,
          "sha512": "e08e65c8faaf1160b0902ecd6b1bf6bc4e588938214f230a24630ab2fda2dd26c5dc938e51484a56acec39503aa11f385636f342171877f74786c9a45456422d",
          "sha256": "8e1b13aa736c43ff7aaa0023569108e2685237e5e80ee9736d08b9fb1e70b916",
          "sha1": "a7ba28f32a7c3fee98fdd7e74f740c7717b905d2",
          "md5": "d20b24128db8cdb087d95c3e4379b80a"
        }
      ]
    }
  ]
}
