{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libJOSUtils",
    "version": "1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libJOSUtils-1.3.aar",
          "url": "libJOSUtils-1.3.aar",
          "size": 50959,
          "sha512": "7f6842aebb3ba4e5dfb35cf53efac8d07b3d587ff484cc5b0c2760f33ccb3bc20f12172e0a370a8beafefaa0cc60d32c3584f859a33c68f778034847ca9ac3c9",
          "sha256": "9f7d7761e7e1ca48b59a53d8b064d6760b2835a8f304d02f64044ef05b6b2c3e",
          "sha1": "7dbbba981b9f823f69935b14dc4626353f260570",
          "md5": "b37e2e99cb96fe334b0e0c55615f8a2b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.zhuchao.android",
          "module": "libFBaseUtils",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "com.google.android.things",
          "module": "androidthings",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "libJOSUtils-1.3.aar",
          "url": "libJOSUtils-1.3.aar",
          "size": 50959,
          "sha512": "7f6842aebb3ba4e5dfb35cf53efac8d07b3d587ff484cc5b0c2760f33ccb3bc20f12172e0a370a8beafefaa0cc60d32c3584f859a33c68f778034847ca9ac3c9",
          "sha256": "9f7d7761e7e1ca48b59a53d8b064d6760b2835a8f304d02f64044ef05b6b2c3e",
          "sha1": "7dbbba981b9f823f69935b14dc4626353f260570",
          "md5": "b37e2e99cb96fe334b0e0c55615f8a2b"
        }
      ]
    }
  ]
}
