{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libCallbackEvent",
    "version": "1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libCallbackEvent-1.3.aar",
          "url": "libCallbackEvent-1.3.aar",
          "size": 6827,
          "sha512": "524e99361f899fbe7c16b18d4e13e9a8c4eeb64fe690fa8b89842a2878b4f5a880b9376d655278302a9372c8d14a01890b432f6e315cc48060cd9e5214b336ae",
          "sha256": "5b85fcd2998622256186cd82d25c5904d8fd4fd1dd5feb64e971a5e6f52e556d",
          "sha1": "351eeb5563d89ac7454a8d7f1ada264501bfacdc",
          "md5": "d0456111569ff3bcf903b7608d04e113"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "libCallbackEvent-1.3.aar",
          "url": "libCallbackEvent-1.3.aar",
          "size": 6827,
          "sha512": "524e99361f899fbe7c16b18d4e13e9a8c4eeb64fe690fa8b89842a2878b4f5a880b9376d655278302a9372c8d14a01890b432f6e315cc48060cd9e5214b336ae",
          "sha256": "5b85fcd2998622256186cd82d25c5904d8fd4fd1dd5feb64e971a5e6f52e556d",
          "sha1": "351eeb5563d89ac7454a8d7f1ada264501bfacdc",
          "md5": "d0456111569ff3bcf903b7608d04e113"
        }
      ]
    }
  ]
}
