{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libPlayerUtils",
    "version": "2.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libPlayerUtils-2.7.aar",
          "url": "libPlayerUtils-2.7.aar",
          "size": 214968,
          "sha512": "f2567a7d9e4c129f977f460ebf410a7a5025d4be917fb6c6ea5b1f186c9d4e6a71eaa573817c543d84a9e72c017f6181635265736904576c816a5a4c6e0c6a0d",
          "sha256": "9e61cd0853cf72cbc67cc1b8d42435f5e191e8735df8b2511106475693da6adf",
          "sha1": "b7dae9659cb5fb8c730553ecee8f2b8d524d2999",
          "md5": "1f7835e37b91f0c9838c82328fcb46d1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.zhuchao.android",
          "module": "libEventInterface",
          "version": {
            "requires": "1.6"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libFBaseUtils",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libINetUtils",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libJOSUtils",
          "version": {
            "requires": "1.2"
          }
        }
      ],
      "files": [
        {
          "name": "libPlayerUtils-2.7.aar",
          "url": "libPlayerUtils-2.7.aar",
          "size": 214968,
          "sha512": "f2567a7d9e4c129f977f460ebf410a7a5025d4be917fb6c6ea5b1f186c9d4e6a71eaa573817c543d84a9e72c017f6181635265736904576c816a5a4c6e0c6a0d",
          "sha256": "9e61cd0853cf72cbc67cc1b8d42435f5e191e8735df8b2511106475693da6adf",
          "sha1": "b7dae9659cb5fb8c730553ecee8f2b8d524d2999",
          "md5": "1f7835e37b91f0c9838c82328fcb46d1"
        }
      ]
    }
  ]
}
