{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libPlayerUtils",
    "version": "2.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libPlayerUtils-2.7.aar",
          "url": "libPlayerUtils-2.7.aar",
          "size": 214985,
          "sha512": "8ff542c678b9ffca1fe9c0ea70a68ee800e39e6276abe0ae429ad325a752e29907fe9ef6f9e1331f45a2e7ef10f91a4d27d4d248a1e56489c0e55b5813241440",
          "sha256": "05a2d74ea3dd7b3a2ea493be0149b79733b2097d6ab15d52777901f656f9d8be",
          "sha1": "ca2e8c36190bda3537d5a22cf7c56c3b532f3b8b",
          "md5": "53143101802efc723d1005c046ed85f0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.zhuchao.android",
          "module": "libFBaseUtils",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libINetUtils",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libJOSUtils",
          "version": {
            "requires": "1.3"
          }
        }
      ],
      "files": [
        {
          "name": "libPlayerUtils-2.7.aar",
          "url": "libPlayerUtils-2.7.aar",
          "size": 214985,
          "sha512": "8ff542c678b9ffca1fe9c0ea70a68ee800e39e6276abe0ae429ad325a752e29907fe9ef6f9e1331f45a2e7ef10f91a4d27d4d248a1e56489c0e55b5813241440",
          "sha256": "05a2d74ea3dd7b3a2ea493be0149b79733b2097d6ab15d52777901f656f9d8be",
          "sha1": "ca2e8c36190bda3537d5a22cf7c56c3b532f3b8b",
          "md5": "53143101802efc723d1005c046ed85f0"
        }
      ]
    }
  ]
}
