{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libPlayerUtils",
    "version": "2.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libPlayerUtils-2.7.aar",
          "url": "libPlayerUtils-2.7.aar",
          "size": 214078,
          "sha512": "c87fbd1817a1aadba7279d174f9e066a64540549af0b94de552200f4ffca0a58f5281bbcabcfc3b5282be93355457e050741794571487caad958caba0b50a115",
          "sha256": "d9015224da1a84374defe9f2c32b71c5406f509ae2f55c91cb3d5cb98222bfbe",
          "sha1": "98203eb152970cd2a09afbf784b2775666a7824a",
          "md5": "a645c08660bd4b16b42201efa2d44df9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.videolan.android",
          "module": "libvlc-all",
          "version": {
            "requires": "4.0.0-eap8"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libDecodeCore",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libEventInterface",
          "version": {
            "requires": "1.6"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libFBaseUtils",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libINetUtils",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libJOSUtils",
          "version": {
            "requires": "1.2"
          }
        }
      ],
      "files": [
        {
          "name": "libPlayerUtils-2.7.aar",
          "url": "libPlayerUtils-2.7.aar",
          "size": 214078,
          "sha512": "c87fbd1817a1aadba7279d174f9e066a64540549af0b94de552200f4ffca0a58f5281bbcabcfc3b5282be93355457e050741794571487caad958caba0b50a115",
          "sha256": "d9015224da1a84374defe9f2c32b71c5406f509ae2f55c91cb3d5cb98222bfbe",
          "sha1": "98203eb152970cd2a09afbf784b2775666a7824a",
          "md5": "a645c08660bd4b16b42201efa2d44df9"
        }
      ]
    }
  ]
}
