{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libFOSUtils",
    "version": "1.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libFOSUtils-1.4.1.aar",
          "url": "libFOSUtils-1.4.1.aar",
          "size": 207695,
          "sha512": "ccf3f84ed02db3a764cd4bdc898e1852a16be9f05f890cc9193650e473f84ff135c5bf42136e8e70294949ded4141fcf26637a3c4b332bc2414eef2262cd61e6",
          "sha256": "012732801ded266493a2757a740713bb723bbdb9e53474e5f2671d0c696367bb",
          "sha1": "f8564bc1f8dd31e0962c147264dd121b5ff055af",
          "md5": "f461e8d4102591eff3c92656c3eed617"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.zhuchao.android",
          "module": "libBaseUtils",
          "version": {
            "requires": "2.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "libFOSUtils-1.4.1.aar",
          "url": "libFOSUtils-1.4.1.aar",
          "size": 207695,
          "sha512": "ccf3f84ed02db3a764cd4bdc898e1852a16be9f05f890cc9193650e473f84ff135c5bf42136e8e70294949ded4141fcf26637a3c4b332bc2414eef2262cd61e6",
          "sha256": "012732801ded266493a2757a740713bb723bbdb9e53474e5f2671d0c696367bb",
          "sha1": "f8564bc1f8dd31e0962c147264dd121b5ff055af",
          "md5": "f461e8d4102591eff3c92656c3eed617"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "libFOSUtils-1.4.1-sources.jar",
          "url": "libFOSUtils-1.4.1-sources.jar",
          "size": 77195,
          "sha512": "86c2112ce1b63494bd32c6b96997fb534ee3aacf57a22f8c7a9ce754fe031775aa3ee458354a3ab2008d3cc7f82edb0b44a6f71a69e5c19fdea8f8729f0cc8a1",
          "sha256": "3e47ed67003d297e65bf5bb0a884550b6b4211cff60c123583394fbd487036a3",
          "sha1": "3e7c23f1fa61deeb0b436e60426e63e3e359be49",
          "md5": "da411cdc368248a4cc306b65ed1e0d69"
        }
      ]
    }
  ]
}
