{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libFOSUtils",
    "version": "1.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libFOSUtils-1.4.1.aar",
          "url": "libFOSUtils-1.4.1.aar",
          "size": 208147,
          "sha512": "9f236011778cdab5b22774d19cbd493ff4b5a88632d21386c89aab5856bf367cf54130a9f06cc6f87d839d661596c67bca7129161ef01cb9d61397d98a91f328",
          "sha256": "71fbcc326eb9f442f0c036314784c7006cf7d30fb93cacbd1010e9bab41a731d",
          "sha1": "bc6e5d6c4abc2b9c4e812ab1c84f29d2598d3f77",
          "md5": "65f299b25781c31b9ef4977fc404a5d6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.zhuchao.android",
          "module": "libBaseUtils",
          "version": {
            "requires": "2.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "libFOSUtils-1.4.1.aar",
          "url": "libFOSUtils-1.4.1.aar",
          "size": 208147,
          "sha512": "9f236011778cdab5b22774d19cbd493ff4b5a88632d21386c89aab5856bf367cf54130a9f06cc6f87d839d661596c67bca7129161ef01cb9d61397d98a91f328",
          "sha256": "71fbcc326eb9f442f0c036314784c7006cf7d30fb93cacbd1010e9bab41a731d",
          "sha1": "bc6e5d6c4abc2b9c4e812ab1c84f29d2598d3f77",
          "md5": "65f299b25781c31b9ef4977fc404a5d6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "libFOSUtils-1.4.1-sources.jar",
          "url": "libFOSUtils-1.4.1-sources.jar",
          "size": 77317,
          "sha512": "2996dd14a1558875e5946851ecf2ed7553b32a7b3ce6aad5b757e29136e0b179a28214710a1c549a93c616e153d7aed27b7d69a06d9f04b04201f59ba7327431",
          "sha256": "777621bba923c086f8fec3c5654863b1ba379e24f36b03201cf3803852ef941f",
          "sha1": "e6635d16c6b83f9ffa253510e3711d0417b55d11",
          "md5": "898c38feb34654a1a63e58b0b56c4de6"
        }
      ]
    }
  ]
}
