{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libFOSUtils",
    "version": "1.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libFOSUtils-1.4.1.aar",
          "url": "libFOSUtils-1.4.1.aar",
          "size": 208146,
          "sha512": "8ab5708457e203525e4eb108a2ff841eb350971f11c6346c926c941e1569caf45286f103e7aad3f82fe6f0755d6b395c3edcb3005c5ed140f68e9ef9840f3a7a",
          "sha256": "2157d2d053d436899d4a8adf0a86f91cd7152cbcf22aa3eaff0a44f152003bc2",
          "sha1": "7ae9bd0fd31f13c48ccc303d4b889067ed5b5797",
          "md5": "b12d2fd6043ba6e974baca8817829ba3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.zhuchao.android",
          "module": "libBaseUtils",
          "version": {
            "requires": "2.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "libFOSUtils-1.4.1.aar",
          "url": "libFOSUtils-1.4.1.aar",
          "size": 208146,
          "sha512": "8ab5708457e203525e4eb108a2ff841eb350971f11c6346c926c941e1569caf45286f103e7aad3f82fe6f0755d6b395c3edcb3005c5ed140f68e9ef9840f3a7a",
          "sha256": "2157d2d053d436899d4a8adf0a86f91cd7152cbcf22aa3eaff0a44f152003bc2",
          "sha1": "7ae9bd0fd31f13c48ccc303d4b889067ed5b5797",
          "md5": "b12d2fd6043ba6e974baca8817829ba3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "libFOSUtils-1.4.1-sources.jar",
          "url": "libFOSUtils-1.4.1-sources.jar",
          "size": 77318,
          "sha512": "42aba4cf2db8a8ef808dfa8118c702e55c074d344b3660031a9475afa8597e0de2a97fc777119e6f1a0e61dd9988bdfff8885669959441ddecad231a73cddaaf",
          "sha256": "5ef0d98af6aec4537769f834924e7aa02581896c9cce61d069a604ff7496aeac",
          "sha1": "6e2fd072fc931432ad0e83b4b1dcf146e810832d",
          "md5": "8ac917df118ba0cc6767a7027013d327"
        }
      ]
    }
  ]
}
