{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libFBaseUtils",
    "version": "1.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0-alpha02"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "libFBaseUtils-1.8.aar",
          "url": "libFBaseUtils-1.8.aar",
          "size": 101668,
          "sha512": "2127e5d5b037ea84892e8ff46135d3c11992645cab006ce51b4541a592ab341777702fab1ea1565eeb88bc493776fd7b83798d0b10e108d9543a3cab439b93c0",
          "sha256": "0953c792e29680c8b21eb4523dd7c586596cfb7682a7bcfad05a05b0f1262f97",
          "sha1": "1f29b0b2d36c0f08cf821f45bebf659606bc6700",
          "md5": "4bf85359955530a738f9d8864057dff4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.zhuchao.android",
          "module": "libEventInterface",
          "version": {
            "requires": "1.6"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.0-alpha01"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0-alpha02"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "libFBaseUtils-1.8.aar",
          "url": "libFBaseUtils-1.8.aar",
          "size": 101668,
          "sha512": "2127e5d5b037ea84892e8ff46135d3c11992645cab006ce51b4541a592ab341777702fab1ea1565eeb88bc493776fd7b83798d0b10e108d9543a3cab439b93c0",
          "sha256": "0953c792e29680c8b21eb4523dd7c586596cfb7682a7bcfad05a05b0f1262f97",
          "sha1": "1f29b0b2d36c0f08cf821f45bebf659606bc6700",
          "md5": "4bf85359955530a738f9d8864057dff4"
        }
      ]
    }
  ]
}
