{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libFBaseUtils",
    "version": "1.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0-alpha02"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "libFBaseUtils-1.8.aar",
          "url": "libFBaseUtils-1.8.aar",
          "size": 101540,
          "sha512": "b1e47b588e79922cf63b3fe371f3f83058a05e7068d17d4af17c2e82d37755eadcbdc5dd93450ff4eeac615a03afd9d1e9231e1d7d47cbecd57b718a5c70a55e",
          "sha256": "c7fbb39c76fd9f306133da60056e59f7de881817fbef34ac8d3db991e1bce63a",
          "sha1": "7550896adb088d238f0d15563149d1e73628f649",
          "md5": "086f09b32ca7a1771c626027289cc32d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.zhuchao.android",
          "module": "libEventInterface",
          "version": {
            "requires": "1.6"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.0-alpha01"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0-alpha02"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "libFBaseUtils-1.8.aar",
          "url": "libFBaseUtils-1.8.aar",
          "size": 101540,
          "sha512": "b1e47b588e79922cf63b3fe371f3f83058a05e7068d17d4af17c2e82d37755eadcbdc5dd93450ff4eeac615a03afd9d1e9231e1d7d47cbecd57b718a5c70a55e",
          "sha256": "c7fbb39c76fd9f306133da60056e59f7de881817fbef34ac8d3db991e1bce63a",
          "sha1": "7550896adb088d238f0d15563149d1e73628f649",
          "md5": "086f09b32ca7a1771c626027289cc32d"
        }
      ]
    }
  ]
}
