{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libPlayUtil",
    "version": "2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libPlayUtil-2.3.aar",
          "url": "libPlayUtil-2.3.aar",
          "size": 32963,
          "sha512": "7c046e74fd2dbda9c8d03c29b9e6eac8e79d19c220a1de388e8c4d01cba9ee80438d3f44d3ff63c2810f7ba2802ce9b6255d0a3e3650b47d2fafc16f7a704418",
          "sha256": "aec040fd240d8eda82eeffa3b6b160e8ea60f38e4d0c86592be3e7105f9dec3f",
          "sha1": "13836f5179d6626b6301763ee7060f0eb4f8db5b",
          "md5": "589d76b14600d09b0f0e7d0270e99b26"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.zhuchao.android",
          "module": "libFileUtils",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libDecodeCore",
          "version": {
            "requires": "2.1"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libCallbackEvent",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "libPlayUtil-2.3.aar",
          "url": "libPlayUtil-2.3.aar",
          "size": 32963,
          "sha512": "7c046e74fd2dbda9c8d03c29b9e6eac8e79d19c220a1de388e8c4d01cba9ee80438d3f44d3ff63c2810f7ba2802ce9b6255d0a3e3650b47d2fafc16f7a704418",
          "sha256": "aec040fd240d8eda82eeffa3b6b160e8ea60f38e4d0c86592be3e7105f9dec3f",
          "sha1": "13836f5179d6626b6301763ee7060f0eb4f8db5b",
          "md5": "589d76b14600d09b0f0e7d0270e99b26"
        }
      ]
    }
  ]
}
