{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libGXPlayerUtils",
    "version": "3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libGXPlayerUtils-3.0.aar",
          "url": "libGXPlayerUtils-3.0.aar",
          "size": 206509,
          "sha512": "1ddbc2659ebc03a3b215127778b3c121fb85630e501cd94556427c9c808c50efb88c7585598f4f2ff56f873310aab26fa4a65d279557739480cf5db8b8229bc2",
          "sha256": "187368c9a0e85584286fb8b921f9e2d5879def81d24eaa058a4752f889a1099b",
          "sha1": "ae9bfdc46b8499ca353f495d02205ed71e3fb12a",
          "md5": "9b296c76062dd4a43a7ef8caaf187ef1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.zhuchao.android",
          "module": "libBaseUtils",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libDNetUtils",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libFOSUtils",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "libGXPlayerUtils-3.0.aar",
          "url": "libGXPlayerUtils-3.0.aar",
          "size": 206509,
          "sha512": "1ddbc2659ebc03a3b215127778b3c121fb85630e501cd94556427c9c808c50efb88c7585598f4f2ff56f873310aab26fa4a65d279557739480cf5db8b8229bc2",
          "sha256": "187368c9a0e85584286fb8b921f9e2d5879def81d24eaa058a4752f889a1099b",
          "sha1": "ae9bfdc46b8499ca353f495d02205ed71e3fb12a",
          "md5": "9b296c76062dd4a43a7ef8caaf187ef1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "libGXPlayerUtils-3.0-sources.jar",
          "url": "libGXPlayerUtils-3.0-sources.jar",
          "size": 20600,
          "sha512": "09c88fb205d119a53d051f4a2aa85a5536355de8034725ffbc9e8098b7e560af8cdcc42512fd237f3dbe977554db2e6c106eec687467a1276705c1f11ee37cdf",
          "sha256": "63f55f1e071287f51ada122697845744cffb0639ff25cc6ccc0208a9de214fcc",
          "sha1": "41f78ef33bccb5a4e1e3b38c675e441801175696",
          "md5": "057cf4e5fd72881dcb51d66c5cbf7359"
        }
      ]
    }
  ]
}
