{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libOpenDetection",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "libOpenDetection-1.0.aar",
          "url": "libOpenDetection-1.0.aar",
          "size": 40381227,
          "sha512": "e7f300d627c7640a6fb4a8e1406e8941d7560dceda8603863bdbb9d26fec73c07d99fcc500324b162b93c703aeae058d465a48d850df9433de1e11a322c94fbb",
          "sha256": "a2f0cb4c223753c7af1614c71113056f210da7d3195187e532da51d8147e4425",
          "sha1": "5d7e48159313ca42952f863b632791f120e2b8a7",
          "md5": "d3ca5f6ddd41c2c47f077f50abf75b91"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.zhuchao.android",
          "module": "libFBaseUtils",
          "version": {
            "requires": "2.1"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libOpenComputerVision",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "org.bytedeco",
          "module": "javacv-platform",
          "version": {
            "requires": "1.5.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "libOpenDetection-1.0.aar",
          "url": "libOpenDetection-1.0.aar",
          "size": 40381227,
          "sha512": "e7f300d627c7640a6fb4a8e1406e8941d7560dceda8603863bdbb9d26fec73c07d99fcc500324b162b93c703aeae058d465a48d850df9433de1e11a322c94fbb",
          "sha256": "a2f0cb4c223753c7af1614c71113056f210da7d3195187e532da51d8147e4425",
          "sha1": "5d7e48159313ca42952f863b632791f120e2b8a7",
          "md5": "d3ca5f6ddd41c2c47f077f50abf75b91"
        }
      ]
    }
  ]
}
