{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libOpenDetection",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libOpenDetection-1.0.aar",
          "url": "libOpenDetection-1.0.aar",
          "size": 50879495,
          "sha512": "39015deb96be9cbf8369e645f867ee742f2b77cf23580512f9bdcfb74ef34818e97d33e4b399026b0158146532a6bdc1d211b9f9a4d3d0af4426a6a253620460",
          "sha256": "a10c9c35a35ba6063b069890f9eafd94091a7ce3122ba0bf0726a64f5985a9ab",
          "sha1": "05ea30c4ad541a34979cfdd73a6afd16a3e18963",
          "md5": "b87b5b3b9059c2cd96436bc23704d949"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.zhuchao.android",
          "module": "libOpenComputerVision",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libCallbackEvent",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libFileUtils",
          "version": {
            "requires": "1.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "org.bytedeco",
          "module": "javacv-platform",
          "version": {
            "requires": "1.5.7"
          }
        }
      ],
      "files": [
        {
          "name": "libOpenDetection-1.0.aar",
          "url": "libOpenDetection-1.0.aar",
          "size": 50879495,
          "sha512": "39015deb96be9cbf8369e645f867ee742f2b77cf23580512f9bdcfb74ef34818e97d33e4b399026b0158146532a6bdc1d211b9f9a4d3d0af4426a6a253620460",
          "sha256": "a10c9c35a35ba6063b069890f9eafd94091a7ce3122ba0bf0726a64f5985a9ab",
          "sha1": "05ea30c4ad541a34979cfdd73a6afd16a3e18963",
          "md5": "b87b5b3b9059c2cd96436bc23704d949"
        }
      ]
    }
  ]
}
