{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libOpenDetection",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libOpenDetection-1.0.aar",
          "url": "libOpenDetection-1.0.aar",
          "size": 50880063,
          "sha512": "e003dc35a468b6143ebc0628f618dda4972f294eba3c6ef6cb1ec8081c6ea5b2381bde49e0069d3fadf2f111fe8117bbd13e0b35d8331af61c1545b106aa561b",
          "sha256": "0d430f9ce2b0e6649681f4e13ec5fb3a3c7b9dba030d29e3ae4349e50a1dc253",
          "sha1": "88b85d05c19e116fc42e13cdc30e30817988c83a",
          "md5": "a7f70956fdce894fc9c15902e33a3271"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.zhuchao.android",
          "module": "libOpenComputerVision",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libEventInterface",
          "version": {
            "requires": "1.6"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libFBaseUitls",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0-alpha02"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "org.bytedeco",
          "module": "javacv-platform",
          "version": {
            "requires": "1.5.8"
          }
        }
      ],
      "files": [
        {
          "name": "libOpenDetection-1.0.aar",
          "url": "libOpenDetection-1.0.aar",
          "size": 50880063,
          "sha512": "e003dc35a468b6143ebc0628f618dda4972f294eba3c6ef6cb1ec8081c6ea5b2381bde49e0069d3fadf2f111fe8117bbd13e0b35d8331af61c1545b106aa561b",
          "sha256": "0d430f9ce2b0e6649681f4e13ec5fb3a3c7b9dba030d29e3ae4349e50a1dc253",
          "sha1": "88b85d05c19e116fc42e13cdc30e30817988c83a",
          "md5": "a7f70956fdce894fc9c15902e33a3271"
        }
      ]
    }
  ]
}
