{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libFBaseUitls",
    "version": "1.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0-alpha02"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10"
          }
        }
      ],
      "files": [
        {
          "name": "libFBaseUitls-1.7.aar",
          "url": "libFBaseUitls-1.7.aar",
          "size": 96130,
          "sha512": "5678fae264c662475341acda0b47dd20b8da9af7fe896b383090890deb626e581378ed882aac12f605931186dc231e3b50f9d610425b9d65fee57116c26a1139",
          "sha256": "6dc5a2111cbf7ad61a94ac24bd143053e47d894f8a47a57c394fd7f7724d7f0b",
          "sha1": "ddd6fa5b24b14a5cc1c03601d42c2f75467c9b13",
          "md5": "0a8f6cb0375a6a16fad5a068b7780b34"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.zhuchao.android",
          "module": "libEventInterface",
          "version": {
            "requires": "1.6"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.0-alpha01"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0-alpha02"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10"
          }
        }
      ],
      "files": [
        {
          "name": "libFBaseUitls-1.7.aar",
          "url": "libFBaseUitls-1.7.aar",
          "size": 96130,
          "sha512": "5678fae264c662475341acda0b47dd20b8da9af7fe896b383090890deb626e581378ed882aac12f605931186dc231e3b50f9d610425b9d65fee57116c26a1139",
          "sha256": "6dc5a2111cbf7ad61a94ac24bd143053e47d894f8a47a57c394fd7f7724d7f0b",
          "sha1": "ddd6fa5b24b14a5cc1c03601d42c2f75467c9b13",
          "md5": "0a8f6cb0375a6a16fad5a068b7780b34"
        }
      ]
    }
  ]
}
