{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libCallbackEvent",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libCallbackEvent-1.0.aar",
          "url": "libCallbackEvent-1.0.aar",
          "size": 3611,
          "sha512": "98eb75364791a6b14e720b73ad9b3fb28547491a2ab684935cc09dd73a4276874c8719d8c03b4b16c394387c5bb34a49aaa3507dbcb4bdb38824fe6f7743a605",
          "sha256": "3c20d0b3a36d4e661d1e054e4ac2a3ffa56e05a475dd0d87e20efc9b12f7818e",
          "sha1": "0e4d7833dc0b8d6dbe0b5f2731d634db1477917b",
          "md5": "7af1881fbf94709fe9f1e2e11db6f45d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "libCallbackEvent-1.0.aar",
          "url": "libCallbackEvent-1.0.aar",
          "size": 3611,
          "sha512": "98eb75364791a6b14e720b73ad9b3fb28547491a2ab684935cc09dd73a4276874c8719d8c03b4b16c394387c5bb34a49aaa3507dbcb4bdb38824fe6f7743a605",
          "sha256": "3c20d0b3a36d4e661d1e054e4ac2a3ffa56e05a475dd0d87e20efc9b12f7818e",
          "sha1": "0e4d7833dc0b8d6dbe0b5f2731d634db1477917b",
          "md5": "7af1881fbf94709fe9f1e2e11db6f45d"
        }
      ]
    }
  ]
}
