{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libCallbackEvent",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libCallbackEvent-1.0.aar",
          "url": "libCallbackEvent-1.0.aar",
          "size": 3603,
          "sha512": "f48434857e8d9e6319a7c0ec79f188fa78ee44431983abbef11a007ffe3954161cb43e769c7b750cdd01a5b5c74b9015b948983edd43c0913bc84909bd8093ab",
          "sha256": "d75fe3bd216447d5d24f0b69c4c9f7bcd55d886ff68191549497cc9aabf85b25",
          "sha1": "c370f69d573f3fe5629c21d7eb1f7ffc23f9160b",
          "md5": "f16cf16c41e487783d27bf47f5e3e48b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "libCallbackEvent-1.0.aar",
          "url": "libCallbackEvent-1.0.aar",
          "size": 3603,
          "sha512": "f48434857e8d9e6319a7c0ec79f188fa78ee44431983abbef11a007ffe3954161cb43e769c7b750cdd01a5b5c74b9015b948983edd43c0913bc84909bd8093ab",
          "sha256": "d75fe3bd216447d5d24f0b69c4c9f7bcd55d886ff68191549497cc9aabf85b25",
          "sha1": "c370f69d573f3fe5629c21d7eb1f7ffc23f9160b",
          "md5": "f16cf16c41e487783d27bf47f5e3e48b"
        }
      ]
    }
  ]
}
