{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libCameraController",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libCameraController-1.0.aar",
          "url": "libCameraController-1.0.aar",
          "size": 1811364,
          "sha512": "88452b6cc36f3ac2bfa7971df271f4c0da6d72b99f8866ed3f9761a83d101845ec5a1e668ca96674cacb3a1603e3ffa068f24f0f631cb0701247f380a0c90f3a",
          "sha256": "8e9fc8c9736201fb6102d20d5b4cf493ca0b9082f33d4c9fa881dd7fec3e5f07",
          "sha1": "14dd1db31352a286d524a8bc3e8dbba6a256a087",
          "md5": "79502b9d1358ecc1445445cb22d1ed40"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "libCameraController-1.0.aar",
          "url": "libCameraController-1.0.aar",
          "size": 1811364,
          "sha512": "88452b6cc36f3ac2bfa7971df271f4c0da6d72b99f8866ed3f9761a83d101845ec5a1e668ca96674cacb3a1603e3ffa068f24f0f631cb0701247f380a0c90f3a",
          "sha256": "8e9fc8c9736201fb6102d20d5b4cf493ca0b9082f33d4c9fa881dd7fec3e5f07",
          "sha1": "14dd1db31352a286d524a8bc3e8dbba6a256a087",
          "md5": "79502b9d1358ecc1445445cb22d1ed40"
        }
      ]
    }
  ]
}
