{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libCameraController",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libCameraController-1.0.aar",
          "url": "libCameraController-1.0.aar",
          "size": 1811574,
          "sha512": "725c80abc7d6b65b7e5d3b55a35bb06fdd05570a70c06c700700b3a5eb6b33e05de82bec547b7aeb4de37540f62cb56080a9b457cd3438c1ccd9689a594e8435",
          "sha256": "13effa57af370b27e920711edb4cd7352db4dc4603d9e33acf3b43b699afb662",
          "sha1": "a6b3304b7f103850b52f9230001fc3f706c9bf2d",
          "md5": "7ad975cc6f9a44cecb610f9c964a5fa7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "libCameraController-1.0.aar",
          "url": "libCameraController-1.0.aar",
          "size": 1811574,
          "sha512": "725c80abc7d6b65b7e5d3b55a35bb06fdd05570a70c06c700700b3a5eb6b33e05de82bec547b7aeb4de37540f62cb56080a9b457cd3438c1ccd9689a594e8435",
          "sha256": "13effa57af370b27e920711edb4cd7352db4dc4603d9e33acf3b43b699afb662",
          "sha1": "a6b3304b7f103850b52f9230001fc3f706c9bf2d",
          "md5": "7ad975cc6f9a44cecb610f9c964a5fa7"
        }
      ]
    }
  ]
}
