{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libDNetUtils",
    "version": "2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libDNetUtils-2.1.aar",
          "url": "libDNetUtils-2.1.aar",
          "size": 37375,
          "sha512": "0b7ca2248550420a9b8dafe29bcb33993dddba813c7fc4da122019610b6e3d30b713039ae577bf0a984d1b5e8dc070100346b22b1c5a80d11f2dc422d387319e",
          "sha256": "8fa0fcbd5f3f0b0c8616724d16b6b95924eacb522405c69f113388580c216ba2",
          "sha1": "9ebbf64bdd24dd23aaf8c81deccd6e5e23b72503",
          "md5": "93791ad407ca0438ca29bec5f4b20736"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.zhuchao.android",
          "module": "libBaseUtils",
          "version": {
            "requires": "2.2"
          }
        }
      ],
      "files": [
        {
          "name": "libDNetUtils-2.1.aar",
          "url": "libDNetUtils-2.1.aar",
          "size": 37375,
          "sha512": "0b7ca2248550420a9b8dafe29bcb33993dddba813c7fc4da122019610b6e3d30b713039ae577bf0a984d1b5e8dc070100346b22b1c5a80d11f2dc422d387319e",
          "sha256": "8fa0fcbd5f3f0b0c8616724d16b6b95924eacb522405c69f113388580c216ba2",
          "sha1": "9ebbf64bdd24dd23aaf8c81deccd6e5e23b72503",
          "md5": "93791ad407ca0438ca29bec5f4b20736"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "libDNetUtils-2.1-sources.jar",
          "url": "libDNetUtils-2.1-sources.jar",
          "size": 14555,
          "sha512": "24f28aec1f3fc8c230b69cec99bbf8cacea0b2d8caa297fe54f4d2f03fd65cf8457f2a8a77fec94d502554845551fdb613e9e91e0b631dc0f53a2909b83d268c",
          "sha256": "04a3015d0aaff473aa71074d7ecad3645312f616064382192899ea64b7c0109d",
          "sha1": "718a532cc01fdbc9faf4a7f1651cd756555a5bcc",
          "md5": "f00a73f250715e099baf8165dbbcf920"
        }
      ]
    }
  ]
}
