{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libFileUtils",
    "version": "1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libFileUtils-1.3.aar",
          "url": "libFileUtils-1.3.aar",
          "size": 48970,
          "sha512": "3c2d90ef270938f83f503b45bab8612b492270fd569eee8c0245bb9494fcb8868d36be4cf1920b0892009e871e6ae5cea20fc8bd81cd6d2415dff14ac2fd0e46",
          "sha256": "6083b2a385a616d8d49bf1c99709adfc5fe624df58ac9e38667080999b04e583",
          "sha1": "16023fcd94bb72d5956550593f4920ac30b02691",
          "md5": "46bd386d0fcb97d79a19eac01dce3334"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "libFileUtils-1.3.aar",
          "url": "libFileUtils-1.3.aar",
          "size": 48970,
          "sha512": "3c2d90ef270938f83f503b45bab8612b492270fd569eee8c0245bb9494fcb8868d36be4cf1920b0892009e871e6ae5cea20fc8bd81cd6d2415dff14ac2fd0e46",
          "sha256": "6083b2a385a616d8d49bf1c99709adfc5fe624df58ac9e38667080999b04e583",
          "sha1": "16023fcd94bb72d5956550593f4920ac30b02691",
          "md5": "46bd386d0fcb97d79a19eac01dce3334"
        }
      ]
    }
  ]
}
