{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libFileUtils",
    "version": "1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libFileUtils-1.3.aar",
          "url": "libFileUtils-1.3.aar",
          "size": 48969,
          "sha512": "efe3bf858baca3c35a657dc5cde180ca6090e936aa89c325eb0e80a525c51b7e967b32390c478bede06e7f777c4be68739279a70aceba47d392ef20f962bc4dc",
          "sha256": "7f43aad847afec43ff257072bd07514b432bfbbf2bfc262f6d562d2c6405f206",
          "sha1": "6b0ff3b9356e8c94eb653f46ca8780d4f65bd98b",
          "md5": "f221daa4f4693dfa8ebe8898b70eacac"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "libFileUtils-1.3.aar",
          "url": "libFileUtils-1.3.aar",
          "size": 48969,
          "sha512": "efe3bf858baca3c35a657dc5cde180ca6090e936aa89c325eb0e80a525c51b7e967b32390c478bede06e7f777c4be68739279a70aceba47d392ef20f962bc4dc",
          "sha256": "7f43aad847afec43ff257072bd07514b432bfbbf2bfc262f6d562d2c6405f206",
          "sha1": "6b0ff3b9356e8c94eb653f46ca8780d4f65bd98b",
          "md5": "f221daa4f4693dfa8ebe8898b70eacac"
        }
      ]
    }
  ]
}
