{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libFPersistUtils",
    "version": "1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "libFPersistUtils-1.2.aar",
          "url": "libFPersistUtils-1.2.aar",
          "size": 9540,
          "sha512": "9cf0f6b7e23005e4799a71fe27bc0f73eb0881b1116675fa452f579c97c383ea563b9adb90172788f11251b045be832b34e7de5d99edd95ade0e1d172aa2e554",
          "sha256": "eff7835cb29749198af1d5a7e8390c8e21136bdffb6d4e9941b18cddaaacbcd0",
          "sha1": "0ce58d598e735c2bd7eaeed634cc36e94089716d",
          "md5": "4f206abccd79cf5caf6f21d8075daa88"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.zhuchao.android",
          "module": "libBaseUtils",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "libFPersistUtils-1.2.aar",
          "url": "libFPersistUtils-1.2.aar",
          "size": 9540,
          "sha512": "9cf0f6b7e23005e4799a71fe27bc0f73eb0881b1116675fa452f579c97c383ea563b9adb90172788f11251b045be832b34e7de5d99edd95ade0e1d172aa2e554",
          "sha256": "eff7835cb29749198af1d5a7e8390c8e21136bdffb6d4e9941b18cddaaacbcd0",
          "sha1": "0ce58d598e735c2bd7eaeed634cc36e94089716d",
          "md5": "4f206abccd79cf5caf6f21d8075daa88"
        }
      ]
    }
  ]
}
