{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libGPersistUtils",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "libGPersistUtils-1.0.aar",
          "url": "libGPersistUtils-1.0.aar",
          "size": 201852,
          "sha512": "f9a914da1a810b2f2d57d1f226fd0a987e024b819d430df2f9c88090e047a76fd04d80adceb01b989b3627c66ad768040225cf697f5a8bf6c5b6868efe8684c4",
          "sha256": "0d1666881a4498a77e2c72148ed37e9e833a10c9811f3eb8ef3d34a346385753",
          "sha1": "937ac2e19c277858c9fced97aca62592ce078b45",
          "md5": "3cfa8e840a088f76d5c6b130dd1b621f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libFBaseUitls",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "libGPersistUtils-1.0.aar",
          "url": "libGPersistUtils-1.0.aar",
          "size": 201852,
          "sha512": "f9a914da1a810b2f2d57d1f226fd0a987e024b819d430df2f9c88090e047a76fd04d80adceb01b989b3627c66ad768040225cf697f5a8bf6c5b6868efe8684c4",
          "sha256": "0d1666881a4498a77e2c72148ed37e9e833a10c9811f3eb8ef3d34a346385753",
          "sha1": "937ac2e19c277858c9fced97aca62592ce078b45",
          "md5": "3cfa8e840a088f76d5c6b130dd1b621f"
        }
      ]
    }
  ]
}
