{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libGPersistUtils",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "libGPersistUtils-1.0.aar",
          "url": "libGPersistUtils-1.0.aar",
          "size": 204425,
          "sha512": "156dbf9482ff9517d4b6ff81a2409866cf27ec5d3be2dfed5c5f6abe484d1a190f3b7550a601ccaba49d9b6b07b8c10bd1335f86143735d692b2fb1be8a42aff",
          "sha256": "3e6ea06d3a5771e4a4d811aa47e7548be1fd881bc3194152a5308cd92e61bee5",
          "sha1": "8a28d859dd78461b43f282da0a36d010d6f7bf72",
          "md5": "0655bc4a3daa93b1e13d03268e62fe0c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libFBaseUtils",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "libGPersistUtils-1.0.aar",
          "url": "libGPersistUtils-1.0.aar",
          "size": 204425,
          "sha512": "156dbf9482ff9517d4b6ff81a2409866cf27ec5d3be2dfed5c5f6abe484d1a190f3b7550a601ccaba49d9b6b07b8c10bd1335f86143735d692b2fb1be8a42aff",
          "sha256": "3e6ea06d3a5771e4a4d811aa47e7548be1fd881bc3194152a5308cd92e61bee5",
          "sha1": "8a28d859dd78461b43f282da0a36d010d6f7bf72",
          "md5": "0655bc4a3daa93b1e13d03268e62fe0c"
        }
      ]
    }
  ]
}
