{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libGPersistUtils",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "libGPersistUtils-1.0.aar",
          "url": "libGPersistUtils-1.0.aar",
          "size": 204921,
          "sha512": "87212431e8e46b26947cc283af26064eae83b2b5da24bf15b3366f8dfc517ecc2383e0a5b4d47a3ef2cec9f8d707cedbaad20b59fd919940848c8f13bb56a5d8",
          "sha256": "3a93a9f88e06cecdd262f1eab437e40e6391733938af5f106e7ed9be4ee70140",
          "sha1": "66e789e6e05097d32dd2ddbf3a043df5019630a7",
          "md5": "fe2da866f0014316cdaf825419c22e01"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libFBaseUtils",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "libGPersistUtils-1.0.aar",
          "url": "libGPersistUtils-1.0.aar",
          "size": 204921,
          "sha512": "87212431e8e46b26947cc283af26064eae83b2b5da24bf15b3366f8dfc517ecc2383e0a5b4d47a3ef2cec9f8d707cedbaad20b59fd919940848c8f13bb56a5d8",
          "sha256": "3a93a9f88e06cecdd262f1eab437e40e6391733938af5f106e7ed9be4ee70140",
          "sha1": "66e789e6e05097d32dd2ddbf3a043df5019630a7",
          "md5": "fe2da866f0014316cdaf825419c22e01"
        }
      ]
    }
  ]
}
