{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libVideo",
    "version": "1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libVideo-1.3.aar",
          "url": "libVideo-1.3.aar",
          "size": 27604,
          "sha512": "43faedf254e968599ba474ddf72cb624cdd1632e79f10ac2ed072e1b076b1c68c5ff770fcda25a72e06f87f7f37e33ba29211ffab7f170291c19346c6b70d154",
          "sha256": "bb2fb21175c1944b4dce30e23c73bc1995d10c496e8a4561b7b22b02161ad61c",
          "sha1": "662b639fae937ba303a3777c5f9011a788966493",
          "md5": "28b70866bb309aa60d52b2e0ab726e23"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libCallbackEvent",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libPlayUtil",
          "version": {
            "requires": "2.1"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libNetUtil",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libDataBaseUtil",
          "version": {
            "requires": "2.1"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libFileUtils",
          "version": {
            "requires": "1.2"
          }
        }
      ],
      "files": [
        {
          "name": "libVideo-1.3.aar",
          "url": "libVideo-1.3.aar",
          "size": 27604,
          "sha512": "43faedf254e968599ba474ddf72cb624cdd1632e79f10ac2ed072e1b076b1c68c5ff770fcda25a72e06f87f7f37e33ba29211ffab7f170291c19346c6b70d154",
          "sha256": "bb2fb21175c1944b4dce30e23c73bc1995d10c496e8a4561b7b22b02161ad61c",
          "sha1": "662b639fae937ba303a3777c5f9011a788966493",
          "md5": "28b70866bb309aa60d52b2e0ab726e23"
        }
      ]
    }
  ]
}
