{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libCameraUtils",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libCameraUtils-1.0.aar",
          "url": "libCameraUtils-1.0.aar",
          "size": 28230,
          "sha512": "adf88b76c871ecd31648fcb4ae48c00b476716bb3df8600356f7e2cadffcca57f5f9e166054ee9193596291d7befe0f31d2da2f027e76e37f382c8e49837bd6e",
          "sha256": "c3ec34b7e9e596cc41e5dd93548e24e70e77f97738b5b5dd36b4eb16c2d8c26e",
          "sha1": "e8e10332cb73b5ca5652cb5356ed48b1369d8aa2",
          "md5": "7af80668c2285578f08f18c8ebd31ce1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.zhuchao.android",
          "module": "libBaseUtils",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "2.0.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "libCameraUtils-1.0.aar",
          "url": "libCameraUtils-1.0.aar",
          "size": 28230,
          "sha512": "adf88b76c871ecd31648fcb4ae48c00b476716bb3df8600356f7e2cadffcca57f5f9e166054ee9193596291d7befe0f31d2da2f027e76e37f382c8e49837bd6e",
          "sha256": "c3ec34b7e9e596cc41e5dd93548e24e70e77f97738b5b5dd36b4eb16c2d8c26e",
          "sha1": "e8e10332cb73b5ca5652cb5356ed48b1369d8aa2",
          "md5": "7af80668c2285578f08f18c8ebd31ce1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "libCameraUtils-1.0-sources.jar",
          "url": "libCameraUtils-1.0-sources.jar",
          "size": 14168,
          "sha512": "99e7b18ef4abfc4d095ef54d98db46c514246750feb30d5636dc9ebbad1b33319dd796d6ecdceaa250fbe2f5dc56695dc5edb3aa8d2647d0a76db922740e9f34",
          "sha256": "cbe935bb11a5e8d08abff1f7717d1c027c3936eff90de2113d60038195f26a86",
          "sha1": "4014e8a4bf9b40afb412ed79616d49cf19f4f800",
          "md5": "428e17bdad517d8028314a4d22063652"
        }
      ]
    }
  ]
}
